### ISSUE TITLE
rusEFI at SF

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#100]
sync got broken?

https://sourceforge.net/p/rusefi/code/HEAD/tree/trunk/

fix sync? drop SF? else?

**Comment by chuckwagoncomputing** [comment]
Is SF providing any value at this point?

**Comment by mck1117** [comment]
no

**Comment by chuckwagoncomputing** [comment]
burn it

**Comment by rusefillc** [comment]
"burn" is vague.

I am not sure what are the relevant buttons if any https://webapps.stackexchange.com/questions/42490/can-you-delete-a-project-on-sourceforge

**Comment by mck1117** [comment]
ok well that's pretty dumb, thanks sourceforge

**Comment by mck1117** [comment]
maybe you can open an issue on sourceforge itself? https://sourceforge.net/p/forge/site-support/14223/

**Comment by chuckwagoncomputing** [comment]
When I search "open source ecu" in DuckDuckGo, the SF repo is the 6th result, and the only other rusEFI result on the first page is the Hackaday article about Frankenstein. That's got to be confusing to someone when they go to the repo and see that it hasn't been updated since 2019.

**Comment by rusefillc** [comment]
I wonder if it would be better to drop all files via SVN and keep the "moved to GH" readme?

**Comment by rusefillc** [comment]
https://sourceforge.net/p/rusefi/code/HEAD/tree/firmware_archive/ is the most useful part we need to preserve somewhere

**Comment by duhafnusa4** [comment]
Looks like link works properly. @mck1117 can you validate? If so please close.

**Comment by rusefillc** [comment]
@duhafnusa4 you are scaring me here. how is it working property? it's outdated and confusing is not it?

**Comment by duhafnusa4** [comment]
I meant the physical link working and not dead

**Comment by chuckwagoncomputing** [comment]
@duhafnusa4 So your opinion is that the "moved to" links in the SF repo are enough, and the repo should not be removed?

**Comment by duhafnusa4** [comment]
I don't have an opinion. I just said the link worked. I also just want this ticket to be completed. Can you assist?

**Comment by chuckwagoncomputing** [comment]
As far as I can tell as a relative newcomer, the status quo in this project is that open issues are not of negative value.
I think this ticket only gets closed if the SF repo gets deleted.
My opinion is that it should be deleted, but the situation is slightly better now than it was 6 months ago, as our SEO has somehow improved.

**Comment by mi-hol** [comment]
@rusefillc old files on [sourceforge](https://sourceforge.net/projects/rusefi/files/) should be removed. I'd be happy to own this cleanup, assuming login is provided

![image](https://user-images.githubusercontent.com/22799428/205896751-dcf3ce39-5d01-49a5-a3ba-93c171100e28.png)

**Comment by mi-hol** [comment]
> @rusefillc old files on [sourceforge](https://sourceforge.net/projects/rusefi/files/) should be removed

to be clear I mean "rusefi.r46.zip" with "old files" because SF refers to this as "Download Latest Version"

or

SF feature "sync file with GitHub" feature could be used to have the same versions available on both repos.
This would provide a fail-safe copy via 2 different access paths

**Comment by rusefillc** [comment]
One file removed from https://sourceforge.net/projects/rusefi/files/
