### ISSUE TITLE
Document 'popular vehicles'

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#106]
https://rusefi.com/forum/viewtopic.php?p=38028#p38028

**Comment by rusefillc** [comment]
See also https://github.com/rusefi/rusefi/issues/1810

**Comment by duhafnusa4** [comment]
Im not really sure the purpose of this ticket is clear. 

Questions:

1) Do we want to add more vehicles to the popular vehicles list in TS
2) How many do we want to have?
3) How is this better than REO?

**Comment by duhafnusa4** [comment]
@rusefillc what do you think

**Comment by duhafnusa4** [comment]
closing. no comment/changes for literally years.
