### ISSUE TITLE
google page index shows legacy wiki :(

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#107]
part of the issue is that legacy wiki is at rusefi.com domain while new wiki is at github domain so google does not see new GH wiki as part of rusEFI

![image](https://user-images.githubusercontent.com/48498823/99568337-4b02a180-299d-11eb-879e-fd8d93076fb9.png)

**Comment by duhafnusa4** [comment]
no wiki shows up anymore at all. Is that solution? 

People can click and go to rusefi.com and then go to wiki

<img width="689" alt="rusefi" src="https://user-images.githubusercontent.com/5051341/125512133-e3816252-05db-44bb-a87d-66ae6e8da4ef.png">

**Comment by rusefillc** [comment]
Not solution

What we need is for rusEFI documentation to show up - which is does not at the moment.

@mck1117 any fresh rumours?

**Comment by rusefillc** [comment]
oh shit

we have the file for a while https://github.com/rusefi/rusefi/blob/master/misc/www/robots.txt

but it was not uploaded to actual www since upload is manual :(

anyway let me also make it multi-line

**Comment by rusefillc** [comment]
We now have https://rusefi.com/robots.txt
