### ISSUE TITLE
Release date not visible on https://github.com/rusefi/rusefi/wiki/Download

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#109]
https://github.com/rusefi/rusefi/wiki/Download does not give a trivial way to show release date?

**Comment by duhafnusa4** [comment]
could we make it a table where "file date" is next to the link that shows when it was uploaded? I know this is manual entry (ie more work) but it at least handles the issue. Whoever does the new file should update that date.

**Comment by rusefillc** [comment]
i think improvement not the cost

as long as we have link to releases achieve we are as good as possible
