### ISSUE TITLE
https://github.com/rusefi/rusefi/wiki/HOWTO-quick-start is a bit outdated

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#110]
https://github.com/rusefi/rusefi/wiki/HOWTO-quick-start focuses on Frankenso and discovery which is no longer popular as of today

Can we merge https://github.com/rusefi/rusefi/wiki/Installing-a-PnP-rusEFI-unit-startup-and-test into https://github.com/rusefi/rusefi/wiki/HOWTO-quick-start or something similar?

**Comment by duhafnusa4** [comment]
pages merged https://github.com/rusefi/rusefi/wiki/HOWTO-quick-start

closed ticket.
