### ISSUE TITLE
update logos

### ISSUE THREAD

**Issue by ksmola** [rusefi/rusefi_documentation#116]
[rusefi_logo_vertical.tar.gz](https://github.com/rusefi/rusefi_documentation/files/5759205/rusefi_logo_vertical.tar.gz)
Here's the vertical version of the rusefi logo. 

sites that currently use the old logo and should be updated (there might be more...):
(replace with either vertical or horizontal logo, whatever is more suitable)
- github
- youtube
- facebook
- instagram

**Comment by rusefillc** [comment]
need a trivial way to find files for the next 3 years. we have 'style' folder in primary repo, let's rename style to legacy style and push new style into same folder?

**Comment by ksmola** [comment]
sounds like a plan, I'll PR shortly

**Comment by rusefillc** [comment]
FB likes to circle does it?

![image](https://user-images.githubusercontent.com/48498823/103445967-47bf2e80-4c48-11eb-903a-ac6a76b69191.png)

**Comment by rusefillc** [comment]
instagram loves circles as well

![image](https://user-images.githubusercontent.com/48498823/103445983-6d4c3800-4c48-11eb-9358-ed4c11b8e886.png)

**Comment by ksmola** [comment]
latest PR has wider logos

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/103446851-485cc280-4c52-11eb-8967-086b5f921bdc.png)


![image](https://user-images.githubusercontent.com/48498823/103446853-57437500-4c52-11eb-8203-48fd06a91d79.png)

**Comment by rusefillc** [comment]
hehe 
![image](https://user-images.githubusercontent.com/48498823/103447098-ba360b80-4c54-11eb-817b-f8a6da011a4d.png)

**Comment by ksmola** [comment]
pr'd a tiny version of the wide black-on-orange logo

**Comment by rusefillc** [comment]
zero priority

shall we add "150" into the name? legacy icons had sizes in names because that was sometimes handy

![image](https://user-images.githubusercontent.com/48498823/103451098-c5595d80-4c8d-11eb-9312-ff6c49d93bb7.png)

**Comment by duhafnusa4** [comment]
@ksmola are there any left? Can you verify complete? If so please close ticket.

**Comment by duhafnusa4** [comment]
@ksmola poke.
