### ISSUE TITLE
 add "why mini? why switch from micro on MRE?" to https://github.com/rusefi/rusefi/wiki/Hardware FAQ

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#134]
Anthony (Motorhead1991)  9:44 PM
Any reason we're still using microUSB and not type c?
9:45
Just curiosity

Simon - Orchardperformance  9:46 PM
Cost basically
9:46
Usb c options were limited and expensive
9:46
Mini USB has proven to be a good ballance between durability and cost

Zach Hoobler  9:46 PM
Jlc now has usbc, so might be a consideration to switch?

Anthony (Motorhead1991)  9:46 PM
Makes sense. Micro is pretty ubiquitous

Simon - Orchardperformance  9:47 PM
I believe the usb c was harder to implement tok
9:47
*too

Andrey  9:47 PM
@Zach Hoobler please provide PN of vertical JLC with data lines

Matthew Kennedy  9:47 PM
C is easy to implement, it's just expensive connector

Simon - Orchardperformance  9:47 PM
Thought it resulted in much smaller connections to solder?

Anthony (Motorhead1991)  9:48 PM
So in 10 years when the price drops....

Matthew Kennedy  9:48 PM
I think there exists some connector that omits the superspeed pairs so it can have wider pitch

Simon - Orchardperformance  9:48 PM
And probably only surface mount

Zach Hoobler  9:49 PM
NVM jlc only has horizontal right now :(

Simon - Orchardperformance  9:50 PM
MiniUSB is pretty common on automotive stuff though tbh. My moats stuff is all miniUSB, the Woolwich racing stuff is, quite a few other things iirc

Andrey  9:50 PM
thank you @Zach Hoobler
9:51
@Anthony (Motorhead1991) we use mini USB because our favorite prototyping shop solders it cheaply and more importantly easily for us
:rolling_on_the_floor_laughing:
1

9:51
it's less about price is more about having one less thing to worry about

Simon - Orchardperformance  9:52 PM
That and people broke both the surface mount and through hole microusb

Anthony (Motorhead1991)  9:52 PM
Everything but the Moates Ostrich is mini USB
9:52
It uses a printer cable :grin:

Simon - Orchardperformance  9:52 PM
Ostrich is usb a like proteus
9:53
Proper chokers for max reliability. Never seen one of those break.

Anthony (Motorhead1991)  9:53 PM
Yup. Those cables are a bit harder to find at local shops though IME
9:53
Hondata uses them too

Simon - Orchardperformance  9:54 PM
Sadly true for both miniUSB aswell now. I have taken to keeping some in stock and sending them out if anyone asks for one
9:54
Ugreen on aliepress have done some good ones for me

Anthony (Motorhead1991)  9:54 PM
I haven't looked in a while... I think WorstBuy still stocks them :thinking_face:

Simon - Orchardperformance  9:55 PM
About $5 iirc

Andrey  10:02 PM
any volunteers to add "why mini? why swtich from micro on MRE?" to https://github.com/rusefi/rusefi/wiki/Hardware FAQ? (edited) 

Simon - Orchardperformance  10:04 PM
Create a ticket and I will pick it up in the near future.

Andrey  10:04 PM
@Anthony (Motorhead1991)?
New

Simon - Orchardperformance  10:05 PM

**Comment by duhafnusa4** [comment]
Q and A added to https://github.com/rusefi/rusefi/wiki/Hardware

Closing ticket
