### ISSUE TITLE
"looking for developers" message on boards

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#135]
We need a really short mix of https://github.com/rusefi/rusefi/wiki/Mission-Statement and https://github.com/rusefi/rusefi/blob/master/misc/Strategy_2021.md spelled out on some or many boards

@blundar can you articulate the "We are looking for software developers" in few words?

**Comment by duhafnusa4** [comment]
@blundar this was asked 2 months ago. If not possible please note here so we can have someone else do it. Thanks!

**Comment by duhafnusa4** [comment]
@rusefillc I recommend putting "developers needed!" in admins and others forum signature linking to strategy.

**Comment by rusefillc** [comment]
@duhafnusa4 great idea, done!

![image](https://user-images.githubusercontent.com/48498823/125976514-fc03bb52-deec-435e-a7e1-dd37d2bb9ba7.png)
