### ISSUE TITLE
wiki is ETB heavy makes you wonder if we even support mTB

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#137]
Got feedback that current wiki is so ETB heavy it makes one wonder if we support cable TB

**Comment by chuckwagoncomputing** [comment]
It's not ETB heavy, it's everything else light.

**Comment by mck1117** [comment]
heh, it's ETB heavy because enough people asked that I wrote the howto guide

**Comment by duhafnusa4** [comment]
I am closing this comment. Wiki has info for ETB and MTB.
