### ISSUE TITLE
What shall we do with legacy wiki? wiki1

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#144]
wiki1 https://rusefi.com/wiki/
wiki2-human https://github.com/rusefi/rusefi/wiki/
wiki2-technical https://github.com/rusefi/rusefi_documentation
wiki3 wiki.rusefi.com

Problem: there are a few legacy links to pages like

https://rusefi.com/wiki/index.php?title=Main_Page

See http://www.turbobricks.org/forums/showthread.php?t=329200
See https://www.electronicspoint.com/forums/threads/ecm-jeep-computer-help-iding-the-motherboard-please.285822/

Do we want to ignore and just drop or do we want some nicer solution?

**Comment by chuckwagoncomputing** [comment]
It should at least redirect to the new wiki home page. Anything beyond that is manual labor. I'd suggest having a system in place for it, even if that's just @rusefillc editing his .htaccess to manually add a specific redirect.

**Comment by rusefillc** [comment]
sounds like that's an argument for NOT using legacy rusefi.com/wiki path for "new" wiki

keep rusefi.com/wiki for legacy compatibility and have latest wiki somewhere else

and "somewhere else" could mean wiki.rusefi.com at github.io without SSH and stuff and we have to carefully weigh all pros and cons of wiki.rusefi.com at github.io

**Comment by rusefillc** [comment]
@mck1117 say deny it via robots

i like it

**Comment by mck1117** [comment]
```
User-agent; *

Disallow: /wiki/
```

**Comment by rusefillc** [comment]
https://rusefi.com/wiki is just a redirect HTML now https://github.com/rusefi/web_backend/tree/master/www/wiki
