### ISSUE TITLE
Write an article on how wiki3 contribution process would look like

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#149]
I suspect that I know the answer but we would need a version of documentation workflow for wiki3 at some point

Can we please write this article before we flip any switches?

**Comment by chuckwagoncomputing** [comment]
How and where should I do this? PR an updated Documentation-Workflow.md?

**Comment by rusefillc** [comment]
Can we copy-paste Documentation-Workflow.md to have a draft at a proper URL while not killing PROD version of the article? and we will replace later?

**Comment by rusefillc** [comment]
@chuckwagoncomputing https://github.com/rusefi/rusefi/wiki/Draft-of-new-Documentation-Workflow created

**Comment by chuckwagoncomputing** [comment]
This is part of #205
