### ISSUE TITLE
Standard for Icons Used

### ISSUE THREAD

**Issue by duhafnusa4** [rusefi/rusefi_documentation#154]
We need to standardize Icons used for linking to other pages and whatnot. 

1) Can I just google and use or will that infringe on creator?
2) Should I create custom Icon pack? - this would be annoying
3) Does anyone have icons we can use?

**Comment by rusefillc** [comment]
@ksmola is the boss

**Comment by duhafnusa4** [comment]
@ksmola can you assist?

**Comment by mi-hol** [comment]
@rusefillc did #116 solve this too or is there an open action? in case yes, what exactly?

**Comment by rusefillc** [comment]
my understanding this is about visual improvements for pages like https://github.com/rusefi/rusefi/wiki/AlphaX-4chan and https://github.com/rusefi/rusefi/wiki/Hellen-121-Nissan which currently have too many text links

Still actual, no progress was made :(

**Comment by rusefillc** [comment]
@ElDominio do you see a value? Do you have any web people to provide help with how the pages above look like?

**Comment by rusefillc** [comment]
We have no resources to improve
