### ISSUE TITLE
upload tune WAT?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#156]
https://github.com/rusefi/rusefi/wiki/HOWTO_upload_tune

https://github.com/rusefi/rusefi/wiki/HOWTO-upload-tune

@duhafnusa4 where did you find https://github.com/rusefi/rusefi/wiki/HOWTO_upload_tune bad link which needs to be fixed?

@chuckwagoncomputing that's still us fixing the global page rename :(

**Comment by chuckwagoncomputing** [comment]
deleted HOWTO-upload-tune

**Comment by rusefillc** [comment]
@duhafnusa4 what has started all this? where is the broken link?

**Comment by duhafnusa4** [comment]
Ive spent a lot of time trying to recreate the issue that stemmed from a hellen page but I cannot. For now I will close this ticket, and if I find any dead links I will make a new ticket, instead of making a new page :)
