### ISSUE TITLE
Decide on what DFU tracks we support and why

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#163]
rusEFI console still works via legacy DFU driver.

We do not update rusEFI console to "new" driver only due to dev resources shortage.

Are there any reasons to use STM32 program or shall we stop to confuse users?

**Comment by rusefillc** [comment]
At the moment we clearly document requirement to REMOVE new driver

https://github.com/rusefi/rusefi/wiki/HOWTO-DFU#q-i-have-stm32-bootloader-in-device-manager-and-rusefi-console-does-not-update-firmware-whats-wrong

**Comment by rusefillc** [comment]
Bill brings the question of Windows VS not-Windows

**Comment by BeerMoneyMotorsports** [comment]
I only use stmcube for initial wideband firmware install. End users should not need to use it. They should only use auto dfu and then manual dfu in case of emergency.
