### ISSUE TITLE
1and1 FTP is unreliable

### ISSUE THREAD

**Issue by chuckwagoncomputing** [rusefi/rusefi_documentation#164]
We keep getting errors like this, which leaves things broken.

```
connect failed: Connection refused.
connect failed: Connection refused.
connect failed: Connection refused.
Falling back to PORT instead of PASV mode.
pinouts/proteus/white35.jpg:    Lost data connection to remote host after 32768 bytes had been sent: Broken pipe.
```

**Comment by blundar** [comment]
that could be firewall related.

**Comment by rusefillc** [comment]
We now have https://rusefi.com/docs/pinouts-backup/ one time manual backup

in my opinion we need to push pinout pages into git. those are kind of same thing-ish as .ini files?

also it would be a dream to have a .pdf generated automatically

**Comment by chuckwagoncomputing** [comment]
OK, so using the primary account would mean putting the authentication details or a private key in GH Secrets. Preferably a private key used only for this.

**Comment by chuckwagoncomputing** [comment]
I'm not sure how you've had FTP set up, but typically FTP is scoped to a specific directory, and the rest of the file system is inaccessible. With SSH, if you don't `cd` somewhere, files will by go in the home directory. Have you confirmed that the files were indeed updated on the server?

**Comment by rusefillc** [comment]
I cannot explain it but yes looks like files are updating

![image](https://user-images.githubusercontent.com/48498823/137830018-bf59781e-ba24-4af6-a182-bd40f7200f88.png)

**Comment by rusefillc** [comment]
https://rusefi.com/build_server/autoupdate/

**Comment by rusefillc** [comment]
and https://rusefi.com/build_server/

**Comment by rusefillc** [comment]
broken again :( https://rusefi.com/docs/pinouts/proteus/

**Comment by rusefillc** [comment]
Switching from FTP to SFTP has resolved this issue
