### ISSUE TITLE
Why do we have rusefi_documentation public

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#165]
Q1: does anyone remember if we need rusefi_documentation at all?

Q2: shall we make it private in order to reduce google search results mess?

**Comment by rusefillc** [comment]
Depends on #166

**Comment by rusefillc** [comment]
@chuckwagoncomputing I've just made https://github.com/rusefi/rusefi_documentation/ public again because of

```
It seems that making rusefi/rusefi_documentation private has caused all forks to instead be forks of rusefillc/rusefi_documentation. Now I can't PR or compare to rusefi/rusefi_documentation, only rusefills/rusefi_documentation.
```

![image](https://user-images.githubusercontent.com/48498823/136666470-6eaf8661-4410-4edd-8761-b4cec08b1c25.png)

**Comment by chuckwagoncomputing** [comment]
FWIW, having rusefi_documentation makes contributing to documentation via PR possible for people who aren't part of the documentation group.

**Comment by rusefillc** [comment]
@chuckwagoncomputing huh? I believe that _anyone_ can edit rusEFI wiki, at least the text part?

I am not sure how can people upload images via www to be honest.

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/137832379-58cbf700-7fcc-4bea-90b4-8b5ce01427fc.png)

not member of https://github.com/orgs/rusefi/teams/doc-team/members

**Comment by rusefillc** [comment]
so we have two questions

Q1: why do we need rusefi_documentation NOW, "before" wiki3

Q2: would rusefi_documentation be used for wiki3? technically we can have http://github.com/rusefi/rusefi/wiki be the source for wiki3 generation. I am not proposing I am only saying that I do not understand what is the best/only way for future workflow

**Comment by chuckwagoncomputing** [comment]
Re: Q2:
I don't think you can add images in the Github Wiki interface, but I'm not positive about that.

**Comment by rusefillc** [comment]
Closing @mck1117 @mi-hol @chuckwagoncomputing FYI.
