### ISSUE TITLE
PROBLEM STATEMENT: wiki2-human https://github.com/rusefi/rusefi/wiki is ugly 

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#167]
As of October 6, 2021 https://github.com/rusefi/rusefi/wiki "wiki2-human" is the primary location of rusEFI knowledge.

As is https://github.com/rusefi/rusefi/wiki is definitely ugly.

We were thinking to move https://github.com/rusefi/rusefi/wiki to wiki.rusefi.com (known as "wiki3") because of indexing issue #138 that's no longer an issue. Yet open question if we would have to move https://github.com/rusefi/rusefi/wiki to wiki.rusefi.com just in order to gain L&F freedom.

**Comment by chuckwagoncomputing** [comment]
There is nothing we can do to make Github Wiki more attractive, but Wiki3 exists. We are maintaining both at this time.
