### ISSUE TITLE
Move pinouts to pages.rusefi.com

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#170]
http://pages.rusefi.com is https://github.com/rusefi/rusefi.github.io

We shall move pinouts to pages.rusefi.com/pinouts

**Comment by rusefillc** [comment]
@chuckwagoncomputing we now have https://pages.rusefi.com/pinouts/

See https://github.com/rusefi/rusefi/tree/master/misc/actions

**Comment by rusefillc** [comment]
To be honest I am not sure what's the proper way forward.

I was operating under the wrong? correct? assumption that FTP was hopeless and removal of 1and1 from the flow looked like the only way forward

now that we hope to address the FTP drama by using SFTP maybe we would not need pages?

**Comment by mi-hol** [comment]
@chuckwagoncomputing is there still an open task?
