### ISSUE TITLE
[MOST IMPORTANT ISSUE] We need sidebar

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#173]
GH wiki has custom sidebar with curated content

can we get same on https://rusefi.com/docs/wiki/Home/ ?

**Comment by rusefillc** [comment]
@chuckwagoncomputing I do not understand what is TOS where :( Table of contents? do you mean 

![image](https://user-images.githubusercontent.com/48498823/137804477-d718514f-f063-40c4-81ae-de7fdc2caf58.png)

if you mean above than yes, that's not good in current form - it shows a lot of not important pages. BMW 1100 should not be on top of the https://rusefi.com/docs/wiki/Home/

**Comment by rusefillc** [comment]
@chuckwagoncomputing I am very excited that you are available to help

but in my opinion there is a chance of a miscommunication here :( i am not sure why having all pages indexed is beneficial. in my opinion we need a fully user-defined table of content / sidebar, with only important information visible

Do you know a way to have important links visible on the main URL and not have not important URLs mixed with important?

**Comment by chuckwagoncomputing** [comment]
Yup gotcha. I think we're on the same page now.

**Comment by chuckwagoncomputing** [comment]
Here we go:
![image](https://user-images.githubusercontent.com/1531127/141831484-fadec60f-b31c-4a65-b848-87d1801badba.png)
A sitemap.xml is also generated now, so pages that don't have a link to them should still be indexed.
https://rusefi.com/docs/wiki/sitemap.xml
