### ISSUE TITLE
List of TunerStudio (TS) tips that need updating tooltips

### ISSUE THREAD

**Issue by OrchardPerformance** [rusefi/rusefi_documentation#175]
Base engine settings: 
Number of cylinder 
Displacement 
Firing order
Vehicle weight 
Forced induction? 
Fuel strategy - mention MAF
Debug mode - Needs to offer description of what debug modes do

Limits and Fallbacks:
cut fuel on rpm limit
cut spark on rpm limit
rpm hard limit rpm
Soft limiter range - needs to be clearer that it is the RPM gap from starting the limiter to full limiter and not a limiter RPM like hard limit.
Failed map sensor fall-back - 

trigger type:
total tooth count
missing/skipped tooth number count
operation mode
use only rising edge - just needs to be a bit clearer that it is on for VR and off for Hall 
Trigger angle advance - Needs note to use timing light to verify 
Display logic signals - Needs to be clearer that this only affects the signal show to user in the high speed logger 
Primary channel 
Secondary channel 
invert cam inputs 

Advanced trigger:
cam mode
vvt sync edge - needs crank sensor VR/hall style note
print verbose vvt sync
print verbose trigger 
do not print sync error - Needs note to say when to turn it off

**Comment by OrchardPerformance** [comment]
Just going to start updating them, there are more that are missing or need updating than are ok. 
Listing them all is going to take longer than simply getting on with it. 

If there are critical ones to update just list them here.
@BeerMoneyMotorsports if you want to see how the tool tips work let me know.

**Comment by BeerMoneyMotorsports** [comment]
Sounds good. When writing them, please make them so someone like me can understand them. 🙂

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports @OrchardPerformance what kind of progress do we plan in the next 14 days?

in my opinion we either act or close this ticket and officially give up. this ticket does not look like something to sit open for six months right?

**Comment by mi-hol** [comment]
@rusefillc would #252 solve this issue?

**Comment by rusefillc** [comment]
See also https://github.com/rusefi/rusefi/issues?q=is%3Aissue+is%3Aopen+tooltip+label%3ATS-layout-and-tooltips

**Comment by rusefillc** [comment]
> @rusefillc would #252 solve this issue?

No.

This one is about tiny summary documentation while #252 is about TS referencing wiki

**Comment by mi-hol** [comment]
@rusefillc  previously your statement was 
"in my opinion we either act or close this ticket and officially give up. this ticket does not look like something to sit open for six months right?"
11 months later it seems removing "important" label remains the only correct choice.
What is your view?

**Comment by OrchardPerformance** [comment]
Close, too much has changed in the firmware to make this ticket of use anymore
