### ISSUE TITLE
TS Online Tuning links to empty page

### ISSUE THREAD

**Issue by duhafnusa4** [rusefi/rusefi_documentation#177]
on https://github.com/rusefi/rusefi/wiki/ the linked "TunerStudio online tuning" takes you to 

https://github.com/rusefi/rusefi/wiki/wiki

which shows "create a new page"

**Comment by duhafnusa4** [comment]
launch control does the same thing

**Comment by duhafnusa4** [comment]
Acceleration enrichment - wall wetting/fuel trip/tau factor does the same thing

**Comment by duhafnusa4** [comment]
Digital Dash does the same thing

**Comment by duhafnusa4** [comment]
https://github.com/rusefi/rusefi/wiki/ is big broken @rusefillc

**Comment by BeerMoneyMotorsports** [comment]
"tuner studio online tuning" takes me to https://github.com/rusefi/rusefi/wiki/HOWTO-create-tunerstudio-project which needs to be updated and improved.

**Comment by rusefillc** [comment]
This seems related to https://github.com/rusefi/rusefi_documentation/pull/147 and https://github.com/rusefi/rusefi_documentation/issues/146

@chuckwagoncomputing do you understand root cause of drama? as is I do not understand why 

```
[TunerStudio online tuning](HOWTO-create-tunerstudio-project)|✓
```
becomes

https://github.com/rusefi/rusefi/wiki/wiki/HOWTO-create-tunerstudio-project

(with double "wiki")

**Comment by chuckwagoncomputing** [comment]
The only ones that aren't broken on the home page are the ones that are hard-linked, which is bad and will need to be fixed when/if we move to wiki3.
As to the cause I have no idea, but it sure looks like a Github bug.

**Comment by rusefillc** [comment]
@chuckwagoncomputing any idea where do we report/inquire about that one?

**Comment by chuckwagoncomputing** [comment]
I edited the page but didn't actually change anything and it seems to have re-generated properly.

**Comment by chuckwagoncomputing** [comment]
Wait I take that back. After editing it took me to https://github.com/rusefi/rusefi/wiki , which works. https://github.com/rusefi/rusefi/wiki/ does not work. (note the trailing slash)

**Comment by rusefillc** [comment]
We need to ket GH know either way?

**Comment by chuckwagoncomputing** [comment]
Not really, that's just how links work. The real problem is that we have a link with a trailing slash somewhere.

**Comment by chuckwagoncomputing** [comment]
No I take that back. The links don't need the preceding "wiki/" to work.

**Comment by chuckwagoncomputing** [comment]
https://github.com/github/feedback/discussions/7157

**Comment by mi-hol** [comment]
@chuckwagoncomputing is this still an open issue?

**Comment by chuckwagoncomputing** [comment]
Seems to be working properly.
