### ISSUE TITLE
Home in wiki3 URL

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#184]
At the moment it's https://rusefi.com/docs/wiki/Home/

We need this to work as 

https://rusefi.com/docs/wiki
https://rusefi.com/docs/wiki/

**Comment by rusefillc** [comment]
@chuckwagoncomputing I've attempted
```
RewriteEngine on
RewriteRule   "^/docs/wiki/$"  "/docs/wiki/Home" [R]
```
and
```
RewriteEngine on
RewriteRule   "^/docs/wiki/$"  "/docs/wiki/Home"
```

both do not seem to change anything :(

**Comment by rusefillc** [comment]
that's at /docs/wiki/.htaccess

**Comment by chuckwagoncomputing** [comment]
Oh I think rules apply relative to the .htaccess file location. Try:
```
RewriteEngine on
RewriteRule   "^/$"  "/Home" [R]
```

**Comment by rusefillc** [comment]
with
```
RewriteEngine on
RewriteRule   "^/$"  "/Home" [R]
```
same nothing
https://rusefi.com/docs/wiki/
