### ISSUE TITLE
syntax differences or else?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#186]
why are download links so broken at https://wiki.rusefi.com/Hardware/Proteus/Proteus-Manual/

![image](https://user-images.githubusercontent.com/48498823/141925782-cef5c34e-fc21-4b9d-94a6-376cb35b121c.png)

![image](https://user-images.githubusercontent.com/48498823/141925726-7e732e65-f168-4f91-a41c-c38c11b0a9ad.png)

**Comment by chuckwagoncomputing** [comment]
Wierd syntax fixed:
https://github.com/rusefi/rusefi_documentation/commit/1b90d48c4886c326f246e5ea3e70dcb2c6c92a72

**Comment by rusefillc** [comment]
I've used [[ x ]] on many Hellen landing pages see https://wiki.rusefi.com/Hellen-154-Hyundai/ and other pages linked from https://wiki.rusefi.com/Hellen-One-Platform/ I will need to revist
