### ISSUE TITLE
Joint RE, BMM, H1 ecu logo

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/rusefi_documentation#194]
I tried and failed to make a good looking combined logo.  @duhafnusa4 kindly offered to step in an help.  
![RE_BMM_H1_logo](https://user-images.githubusercontent.com/82395131/148660501-05f3e1bd-e0a5-4388-844b-57bf818db18a.png)

**Comment by duhafnusa4** [comment]
I'll work on it this week and have designs ready to review Wednesday

**Comment by BeerMoneyMotorsports** [comment]
@duhafnusa4 Wednesday was two days ago........tsk tsk

**Comment by duhafnusa4** [comment]
Yeah because marks designer said he was doing it? If not I'll get it done today

**Comment by duhafnusa4** [comment]
What do you think about this? This is a draft obviously, but is this the direction you want to go?

![image](https://user-images.githubusercontent.com/5051341/149565062-c9ae1f07-c4a0-4023-a608-169355cd55c8.png)

**Comment by BeerMoneyMotorsports** [comment]
That has some potential i think.  Im not sure if @rusefillc or @andreika-git want to give any input?  

I want to make sure people BMM with rusEFI.  I get a lot of "im interested in the bmm ecu" and id like it to be "im interested in the RE ecu you distribute".

**Comment by rusefillc** [comment]
I am very flexible, more or less anything works for me.

My personal take - are we sure we should be piling up logos on top of each other? What's the problem statement?
Would small "runs rusEFI firmware" on the unit and Hellen logo on the PCB solve the problem without logo on top of logo?

**Comment by BeerMoneyMotorsports** [comment]
Lets drop the hellen logo because it is on the PCB.  

For the rusEFI, can we say Powered by rusEFI maybe?  maybe off the the left of the mug?

**Comment by BeerMoneyMotorsports** [comment]
@duhafnusa4 maybe something like this?  In RE font?
![2F15792A-EB89-4A82-853A-B9F530971185](https://user-images.githubusercontent.com/82395131/152056507-509b2afb-b561-45fc-8d88-ffe1b3c14428.jpeg)
![B06FADAE-04AA-4523-A782-15D107D9F41C](https://user-images.githubusercontent.com/82395131/152056515-47971df5-8536-4511-a1f0-a9b869210389.jpeg)

**Comment by duhafnusa4** [comment]
something like this?

![image](https://user-images.githubusercontent.com/5051341/152069022-b7524856-b909-451a-bdb2-932dcb330535.png)

**Comment by duhafnusa4** [comment]
![image](https://user-images.githubusercontent.com/5051341/152069321-23ef84c5-d99e-4412-8b89-f4814ebef332.png)

**Comment by rusefillc** [comment]
too much is going on the log in my opinion. i would just have "powered by rusefi" with just black with same font just smaller type

beer money orange with border is readable with my eyes

"powered" orange with black shade is annoying my eyes specifically your eyes might vary

**Comment by duhafnusa4** [comment]
So what do you think, just black? What Font did you use for your stuff @BeerMoneyMotorsports ?

**Comment by BeerMoneyMotorsports** [comment]
Invert the powered colors. Unfortunately i do not know the font.

**Comment by BeerMoneyMotorsports** [comment]
@duhafnusa4 Lets try the Powered line with current colors inverted and also just black.  Font can remain the same as i do not know what font was originally used.

**Comment by duhafnusa4** [comment]
> @duhafnusa4 Lets try the Powered line with current colors inverted and also just black. Font can remain the same as i do not know what font was originally used.

OK sounds good.

**Comment by duhafnusa4** [comment]
![BMM_RE](https://user-images.githubusercontent.com/5051341/160298362-8d0ff096-033d-4c30-9bf0-c71e8a2ed268.png)

**Comment by duhafnusa4** [comment]
![BMM_RE_2](https://user-images.githubusercontent.com/5051341/160298484-68107ba6-eb90-4eca-94c3-0af7f41c223f.png)
