### ISSUE TITLE
wiki clean-up for Mercedes content

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#197]
We have a bunch of random OEM Merc schematics very poorly structured on the wiki

At the moment we mostly care about stuff related to 128 hellen - shall structure pages better?

**Comment by shadowm60** [comment]
I have started this locally, progress is slow but i am on it.

**Comment by abelom** [comment]
@shadowm60 what is the URL for _your_ _exact_ schematics on rusEFI wiki? :)

**Comment by rusefillc** [comment]
@shadowm60 yes need your vehicle schematics and need some easy to navigate way to it

**Comment by rusefillc** [comment]
@shadowm60 question about 

https://github.com/rusefi/rusefi/wiki/Vault-Of-Mercedes-OEM#m111---i4

new link caption is "OEM Wiring harness" which implies that it's for universal OEM Wiring harness for ANY M111

I believe that's not the case? shall we add some important details into "OEM Wiring harness" text like year? mention EUDM maybe?

**Comment by duhafnusa4** [comment]
the pnp is for pre evo motors (2002 or older) and you can use this picture which shows the differences. 

![2-28-2022 10-54-50 AM](https://user-images.githubusercontent.com/5051341/156025165-24453a74-b0b1-461d-80a6-f3390f2f8289.png)

**Comment by duhafnusa4** [comment]
I would add this picture to help differentiate Pre and Post evo engines (our pnp ecu is for pre) 

![2-28-2022 10-54-50 AM](https://user-images.githubusercontent.com/5051341/156025557-3edebf15-b9ba-4e83-8b60-88e4362c0920.png)

**Comment by rusefillc** [comment]
@shadowm60 ^^^ golden content!

**Comment by mi-hol** [comment]
@shadowm60 is there anything left to be done or should ir be closed?

**Comment by shadowm60** [comment]
To be honest i did everythink i could come up with, i think we can close and open new ticket if we have direct req for something?
