### ISSUE TITLE
Some search results links are broken

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#200]
open https://wiki.rusefi.com/
search for "ETB Error"

One of search results is https://wiki.rusefi.com/Vaults/Vault_Smart_ECU/#fatal-errors

which does not seem to render well for me

![image](https://user-images.githubusercontent.com/48498823/150652962-c941219b-85cf-4d15-8f0b-7b3ed09060f5.png)

**Comment by chuckwagoncomputing** [comment]
Fixed with https://github.com/rusefi/web_backend/commit/04dda25a23a219e0e955384526d2d74740db6265
