### ISSUE TITLE
What's our goal with google search results?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#201]
At the moment https://www.google.com/search?q=HOWTO+M73+v12+on+Proteus returns https://rusefi.com/docs/wiki/HOWTO/HOWTO-M73-v12-on-Proteus/ which properly redirects to https://wiki.rusefi.com/HOWTO/HOWTO-M73-v12-on-Proteus/

Do we expect this to change say in a week or two?

**Comment by rusefillc** [comment]
See #189

**Comment by chuckwagoncomputing** [comment]
Yes this should change.

**Comment by rusefillc** [comment]
Not yet.

**Comment by chuckwagoncomputing** [comment]
Maybe you should [request a recrawl](https://developers.google.com/search/docs/advanced/crawling/ask-google-to-recrawl)
You could submit the sitemap which is at https://wiki.rusefi.com/sitemap.xml
Also see the Index Status report and URL Inspection tool linked from that Google document.

**Comment by chuckwagoncomputing** [comment]
Looks like it's showing up on DuckDuckGo, but not on Google. @rusefillc have you done anything from my last comment yet?

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/154822993-d771b955-52e1-4fed-aa8b-6ad92263534e.png)

**Comment by rusefillc** [comment]
I was planning to request the recrawl and totally forgot to do so. Doing it now because it's totally the right thing to do.

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/154823046-1a36944c-713e-4d36-9943-5c2c59384c06.png)

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/154823113-9b364291-3f26-410e-b95d-a8516ea51053.png)

**Comment by rusefillc** [comment]
Note "Dec 31, 2021" not sure if that's the global "Last crawled"

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/154823151-c5f03933-955a-467e-84d6-d6c5afa4a877.png)

![image](https://user-images.githubusercontent.com/48498823/154823163-5b87bbe4-782a-4cd9-a383-e3132da6a058.png)

**Comment by chuckwagoncomputing** [comment]
Looks good. I guess we wait a few days/weeks and see if it shows up.

**Comment by rusefillc** [comment]
things got worse? no wiki result returned any more?

**Comment by chuckwagoncomputing** [comment]
Looks like the status of 347 pages is:
Discovered - currently not indexed: The page was found by Google, but not crawled yet. Typically, Google wanted to crawl the URL but this was expected to overload the site; therefore Google rescheduled the crawl. This is why the last crawl date is empty on the report.

and 14 are
[Crawled](https://support.google.com/webmasters/answer/7643010) - currently not indexed: The page was crawled by Google, but not indexed. It may or may not be indexed in the future; no need to resubmit this URL for crawling.

48 pages are fully indexed.
So I guess we wait some more?

**Comment by chuckwagoncomputing** [comment]
We're up to 65 fully indexed. Disappointing.
Also, I noticed that Google corrects "HOWTO" to "HOW TO", and then that particular page doesn't show up, but if you click on "Search instead for HOWTO M73 v12 on Proteus", it's the first result. Frustrating.

**Comment by rusefillc** [comment]
good news:
https://www.google.com/search?q=rusefi+dfu+button

includes https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjnxvb25KP6AhVxAjQIHXtQAUMQFnoECAwQAQ&url=https%3A%2F%2Fwiki.rusefi.com%2FHOWTO%2FHOWTO-Update-Firmware%2F&usg=AOvVaw3o6K1GoEhFSutRYHb3jEHx

**Comment by chuckwagoncomputing** [comment]
Where is the wiki hosted? It's on 1&1 right? Is it possible that you don't have enough bandwidth for Google to crawl without overloading your hosting?
As a reminder, this is the official explanation from Google:

Discovered - currently not indexed

The page was found by Google, but not crawled yet. Typically, Google wanted to crawl the URL but this was expected to overload the site; therefore Google rescheduled the crawl. This is why the last crawl date is empty on the report.

**Comment by mck1117** [comment]
how does google even know that it would be expected to overload you?

**Comment by chuckwagoncomputing** [comment]
I assume it measures the download rate while indexing a few pages.

**Comment by mi-hol** [comment]
redirects to https://wiki.rusefi.com/HOWTO/HOWTO-M73-v12-on-Proteus/ now, therefore closing

**Comment by rusefillc** [comment]
🥳 🎈 @chuckwagoncomputing we did it! YOU did it!!!
