### ISSUE TITLE
Some rusefi.com/s links are out of date

### ISSUE THREAD

**Issue by chuckwagoncomputing** [rusefi/rusefi_documentation#207]
#  OKish?

!https://rusefi.com/s/trigger
https://rusefi.com/s/lua

# improved
https://rusefi.com/s/vvt
https://rusefi.com/s/debugmode
https://rusefi.com/s/fuel
https://rusefi.com/s/etb
https://rusefi.com/s/tpstps

Some of these link to Wiki1 pages, some link to Wiki2 pages, and some link to Wiki2 pages that don't exist.

**Comment by rusefillc** [comment]
We have an issue with https://github.com/rusefi/web_backend/issues/146?

**Comment by chuckwagoncomputing** [comment]
Why not point to wiki3?

**Comment by rusefillc** [comment]
I am happy to use wiki3, just a bit lost if we are using wiki3 or not yet

**Comment by mi-hol** [comment]
@rusefillc I understood in our "intro session" that wiki3 is active, hence can this be closed?

**Comment by rusefillc** [comment]
#167 says that wiki2-human is still primary

**Comment by rusefillc** [comment]
@mi-hol ?

**Comment by mi-hol** [comment]
how can I help?

**Comment by rusefillc** [comment]
I am confused. What is the open problem statement? I am not aware f anything being broken

**Comment by mi-hol** [comment]
> What is the open problem statement?

Just needed time to digest answer.
