### ISSUE TITLE
Basically I don't understand where I'd put crank sensor, VSS, TPS, MAP, and Cam position sensor.

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#209]
Here's a signal

![image](https://user-images.githubusercontent.com/48498823/154823295-45852877-aca7-4630-9f49-790dcebc72af.png)

![image](https://user-images.githubusercontent.com/48498823/154823302-58dd3f01-2574-4fc0-810a-137b67d35825.png)

**Comment by chuckwagoncomputing** [comment]
FWIW the pinout page has pins labeled with TPS and MAP in the function field. He appears to be looking at the Proteus 0.2 Wiring wiki page.

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/154823469-cfd8bf8e-0c97-449a-a039-422be2b48dc1.png)

**Comment by rusefillc** [comment]
progress was made
