### ISSUE TITLE
What's the plan for wiki2-human https://github.com/rusefi/rusefi/wiki

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#210]
Once we move to https://wiki.rusefi.com/ do we want to remove or adjust https://github.com/rusefi/rusefi/wiki in order to reduce potential confusion between https://github.com/rusefi/rusefi/wiki and https://wiki.rusefi.com/?

to some expend that depends on if we can easily support both or not

**Comment by mi-hol** [comment]
I got confused hence opened https://github.com/rusefi/rusefi/issues/4749 
Would suggest to fix this with high priority

**Comment by chuckwagoncomputing** [comment]
I'm closing this. The decision for now is to maintain both. If the question comes up again, we can open a new issue.
