### ISSUE TITLE
BMW 760 side sticker

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#211]
I have "green" grey vehicle
![low_760](https://user-images.githubusercontent.com/48498823/156298909-8dc4f652-c237-4ea4-a816-8bb7c202f71d.jpg) and @NMSTEC is available to print side vinyl sticker

**Comment by rusefillc** [comment]
@ksmola what could be done to make it look less horrible?

target audience: I am thinking to visit a few local dyno shops and I am looking to make the 760 look like official rusEFI vehicle

**Comment by mi-hol** [comment]
@rusefillc can this be closed?

**Comment by rusefillc** [comment]
No plans of progress
