### ISSUE TITLE
Universal analytics will not be supported after  July 1, 2023. must change to Google Analytics 4.

### ISSUE THREAD

**Issue by pk386** [rusefi/rusefi_documentation#215]
@ksmola, To be honest I don't know what has to happen. I just got big scary banner saying will not be supported after July 1st 2023....

https://support.google.com/analytics/answer/10759417

**Comment by rusefillc** [comment]
C'mon it's a year out!

**Comment by mi-hol** [comment]
@rusefillc it seems this issue is in the wrong repository.
Shall I move it to rusefi/web_backend via "transfer issue"?

**Comment by rusefillc** [comment]
closing since no one knows what is the problem. Let's re-create once/if anyone knows what is broken
