### ISSUE TITLE
text right on pins mode

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#222]
can we have a mode where text for all pins goes right above pins photo?

i.e. instead of 
![image](https://user-images.githubusercontent.com/48498823/175564497-a74dc891-58dc-4e12-b739-dc711ea90976.png)

can we have closer to 

![image](https://user-images.githubusercontent.com/48498823/175564550-9a725efc-8fd3-4bc7-8c3c-c4a814e982ae.png)

as for XY problem - sometimes one pic/table is more efficient

no idea how to implement in terms of mode switch or not, in terms of image scale or not

**Comment by chuckwagoncomputing** [comment]
I might be able to figure something out. One thing that will make it difficult is that we don't have a "YAML ground truth" for that kind of label. The 'type' field isn't specific enough, and the 'function' field is too long.

**Comment by rusefillc** [comment]
overall we lack clear consistent best practice

* some boards append pin numbers manually
* overall TS vs function separation is unclear


we either need 3rd text version or a clean-up :)

**Comment by chuckwagoncomputing** [comment]
Suppose the label in TS were "<pin number> - <the text from the above MRE table>"
Would that be sufficient information for the end user to have in front of them in TS, or is there currently important information in the current TS Name field that the user would loose?

If it would be enough, I propose we make the TS Name field 4 or 5 letters max, and combine the pin number and TS name when generating the INI.

**Comment by mi-hol** [comment]
@rusefillc a decision seems required

**Comment by chuckwagoncomputing** [comment]
What do you think of this as a solution?

## Cons
  - Requires hovering
  - Won't work on mobile

## Pros
  - Doesn't require restricting the length of the info text
  - Doesn't require making the text smaller to fit

https://user-images.githubusercontent.com/1531127/235257980-08d37d3a-edd9-4aed-ab58-9b6ce9d1dece.mp4

**Comment by mi-hol** [comment]
> * Won't work on mobile

Could you please elaborate on reason(s) for this?
From my view this is the main issue preventing acceptance

**Comment by chuckwagoncomputing** [comment]
I was thinking that you couldn't hover on mobile, but it does show up if you tap on a pin.
![Screenshot_20230429-080652_Firefox Nightly](https://user-images.githubusercontent.com/1531127/235304168-437deee5-22f6-490e-a9df-ea44547d43cc.png)

**Comment by chuckwagoncomputing** [comment]
I have added this to the latest release of interactive-pinout. It's an optional feature that requires adding an `info-column` parameter in the workflow.

@rusefillc If you like this, I can PR an updated workflow file to use this.

**Comment by rusefillc** [comment]
@chuckwagoncomputing yes please PR!

**Comment by rusefillc** [comment]
https://rusefi.com/docs/pinouts/microrusefi/ looks pretty cool thank you @chuckwagoncomputing
