### ISSUE TITLE
Hellen NB2 link takes you to wiki landing page

### ISSUE THREAD

**Issue by duhafnusa4** [rusefi/rusefi_documentation#225]
@BeerMoneyMotorsports When I click on the NB2 link (https://github.com/rusefi/rusefi/wiki/Hellen72 shown in image below) it links to the rusefi wiki landing page. 

![image](https://user-images.githubusercontent.com/5051341/176201729-f17d1b17-807c-4b09-89aa-bc56cbc00770.png)

Where is the NB2 Hellen page?

**Comment by duhafnusa4** [comment]
OK I found it here.

https://github.com/rusefi/rusefi/wiki/Hellen-NB2

Can I fix link and change it to https://github.com/rusefi/rusefi/wiki/Hellen-NB2 ?

**Comment by rusefillc** [comment]
@duhafnusa4 yes please attempt to fix link accorind to docs workflow

**Comment by duhafnusa4** [comment]
Where is the rev F schematic and iBom?

**Comment by duhafnusa4** [comment]
This is the connector correct?

![image](https://user-images.githubusercontent.com/5051341/176225958-4747f49b-c707-49f7-b354-43b6f9bad201.png)

**Comment by BeerMoneyMotorsports** [comment]
That is the connector.  
[hellen72_NB2-f-schematic.pdf](https://github.com/rusefi/rusefi_documentation/files/9004486/hellen72_NB2-f-schematic.pdf)

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/wiki/Hellen-One-Platform link fixed

**Comment by rusefillc** [comment]
NB2-F added to https://github.com/rusefi/rusefi/wiki/Hellen-NB2

**Comment by duhafnusa4** [comment]
Why on Miata hellen do we call some by year and some by chassis?

I suggest we change it to
Miata NA
Miata NB1
Miata NB2

![image](https://user-images.githubusercontent.com/5051341/176305951-284900a8-ddc5-48d0-bd1a-905595e51737.png)

**Comment by BeerMoneyMotorsports** [comment]
the 90-97 NA chassis is split between two ecus.  Unfortunately it is  not a clean split.  There are enough pinout differences, that we cannot use one ecu for all of them.  I would certainly love a cleaner naming method.

90-95 cover NA6 and NA8
96/97 cover NA8 with OBD

**Comment by BeerMoneyMotorsports** [comment]
That looks backwards depending on the view you are using.  see pic below is the back of the connecter where the wires insert.

![image](https://user-images.githubusercontent.com/82395131/176496551-9ff55b8c-6d09-470f-901e-bbbc84578ccd.png)

**Comment by mi-hol** [comment]
@rusefillc how to deal with the new issue in [comment](https://github.com/rusefi/rusefi_documentation/issues/225#issuecomment-1169428849) ?
I'd recommend to open a new issue as the issue from title seems solved.

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports uses his own tracking and priorities, closing
