### ISSUE TITLE
Document 12 tooth trigger

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#227]
https://github.com/rusefi/rusefi/wiki/All-Supported-Triggers should explain usages of 

![image](https://user-images.githubusercontent.com/48498823/177211947-0875c25a-c07a-4d34-b89e-c8a53a52b228.png)

**Comment by rusefillc** [comment]
See also https://rusefi.com/forum/viewtopic.php?p=45801&sid=79166fc0cd1805031193243a839e6322#p45801

**Comment by rusefillc** [comment]
@mck1117 please increase priority of this

See also #241

**Comment by mi-hol** [comment]
todo:  on https://github.com/rusefi/rusefi/wiki/All-Supported-Triggers
verify below text for relevance
```
See 'trigger decoding' in [Doxygen](http://rusefi.com/docs/html/)

May, 2020: Subaru SVX added

April, 2020: Honda K 12+1 added.

April, 2020: Renix 44-2-2 added.

Dev note: unit_tests executable produces triggers.txt file - gen_trigger_images.bat reads triggers.txt and produces these .png files. TODO: automate this further?
```

**Comment by mi-hol** [comment]
@mck1117 Hi Matt, may I kindly remind about this open action?
