### ISSUE TITLE
Rusefi Forum Link goes to overview not wiki 

### ISSUE THREAD

**Issue by moistbrochure** [rusefi/rusefi_documentation#230]
The "about rusefi" link on the forum main page links to the overview page: 
![image](https://user-images.githubusercontent.com/108901504/178034553-d31f2ce7-dcf7-4965-b4ba-9e4e6961f93f.png)
https://github.com/rusefi/rusefi/wiki/overview

The correct links for all details are on the page: https://github.com/rusefi/rusefi/wiki
This is the real "home" page.

**Comment by rusefillc** [comment]
https://rusefi.com/forum/ about now points to proper wiki home

open question when shall we change link to wiki.rusefi.com but that's for a different day
