### ISSUE TITLE
Document firmware upgrade process or make existing documentation more visible

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#233]
See https://rusefi.com/forum/viewtopic.php?p=46065#p46065

**Comment by mi-hol** [comment]
"https://github.com/rusefi/rusefi_documentation/commit/b8cc5af30eccbf44e9a14986bccac7a127fe5707" addressed this already to some extend.

Does Tunerstudio actively check for new  **released firmware versions** ?

**Comment by rusefillc** [comment]
@mi-hol no.
