### ISSUE TITLE
HowTo - Test changes in Wiki before creating PR - seems missing

### ISSUE THREAD

**Issue by mi-hol** [rusefi/rusefi_documentation#249]
Issue:
 I wanted to make wording consistent in navigation bar of wiki to avoid confusion.
Specific example is:
Change "microRusEFI" to read "MicroRusEFI (MRE)"

I assume to have found the name mapping for navigation bar in  mkdocs/mkdocs.yaml 
But how can I make sure this assumption is correct without creating a PR?

Risk:
In case my assumption was wrong, worst case a PR could screw up the whole wiki.

I'm happy to create such a HOWTO doc but hope someone can just give me the necessary step already by pointing to an issue, forum post or other source.

**Comment by chuckwagoncomputing** [comment]
I think this has been satisfactorily solved.
