### ISSUE TITLE
Sync TunerStudio help with wiki3

### ISSUE THREAD

**Issue by mi-hol** [rusefi/rusefi_documentation#252]
Issue:
Help texts in TS don't seem to use wiki content

example:
![image](https://user-images.githubusercontent.com/22799428/201903457-dabe942b-7452-48b7-9aff-81b5db3880f5.png)

Requirement:
find an approach to have application "Help" use wiki content

Solution idea:
- use a "Progressive Web App" (PWA) for "Help" text that saves web content for offline use and refreshes it at every startup

**Comment by chuckwagoncomputing** [comment]
I don't understand this issue. Are you proposing that we somehow replace TS's built in help with our own? Is this even possible?

**Comment by mi-hol** [comment]
not feasible
