### ISSUE TITLE
Hide/remove all references to discovery/frankenso & self-assembly of microRusEFI and Proteus 

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#259]
These days we target people who have purchased fully assembled hardware

Too much of documentation referencing discovery board or Frankenso is pretty much obsolete now. 
We shall mark/move documentation referencing self-assembly of microRusEFI and Proteus a bit away from the most visible path.
While we should not _remove_ it we shall definitely _hide_ it or _mark_ it.

**Comment by rusefillc** [comment]
@mi-hol would you be available and interested to locate such pages? just having a list would be a great help towards deciding how we hide it

**Comment by mi-hol** [comment]
> locate such pages?

doesn't GH search like https://github.com/rusefi/rusefi_documentation/search?q=Frankenso produce the list of files?

**Comment by mi-hol** [comment]
to make this an actionable task a clear definition of "what should be done" is needed. WWhile we should not remove it we shall definitely hide it or mark it." is unfortunately **not** actionable

**Comment by rusefillc** [comment]
Do not see actionable items or specific questions.
