### ISSUE TITLE
wiki3 references wrong download URL after sidebar was used to navigate

### ISSUE THREAD

**Issue by mi-hol** [rusefi/rusefi_documentation#262]
https://wiki.rusefi.com/Home/  shows
![image](https://user-images.githubusercontent.com/22799428/206927134-7ccd3364-c88b-4c6f-91fc-aa0ecb1d3405.png)
Image uses URL https://wiki.rusefi.com/Home/Download
but this URL has no content to show/download
![image](https://user-images.githubusercontent.com/22799428/206927065-1ee1f4b1-1b5c-4d16-a3a7-e7097a261925.png)

next menu item "Download" uses the correct URL https://wiki.rusefi.com/Download/
![image](https://user-images.githubusercontent.com/22799428/206927194-b970cc3f-2ca8-4170-a21c-c3ed6a857be3.png)

**Comment by rusefillc** [comment]
I am very confused see #267

**Comment by rusefillc** [comment]
I open in Chrome
I mouse over image with the box

I see status promising https://wiki.rusefi.com/Download/

I click on the image and I get https://wiki.rusefi.com/Download/

![image](https://user-images.githubusercontent.com/48498823/207500610-0d24a160-af66-4eb3-ac99-864d0e243830.png)

Does this contradict this issue statement or do I get it wrong or was it already fixed?

**Comment by mi-hol** [comment]
> Does this contradict this issue statement

yes and no because I used a different URL, where the link is still wrong
![image](https://user-images.githubusercontent.com/22799428/207560759-58d1018c-5c3e-4944-b537-57973d4b4f9f.png)
Could you please verify using https://wiki.rusefi.com/Home/
This URL is used after navigation from left sidebar is used
