### ISSUE TITLE
is  ionos (formerly 1&1) used to host any content?

### ISSUE THREAD

**Issue by mi-hol** [rusefi/rusefi_documentation#264]
https://github.com/rusefi/rusefi_documentation/issues/201#issuecomment-1254042327 raises the question and I found a related bug in in #262 .
In combination this could potentially explain the bad google search results mentioned #201 

@rusefillc is the used infrastructure perhaps somewhere documented or could someone summarize it here?

**Comment by rusefillc** [comment]
Yes https://www.ionos.com/ is the hosting provider for rusefi.com but how is this related? not the "cloud" option just shared hosting.
