### ISSUE TITLE
Add link to wiki for downloading history versions

### ISSUE THREAD

**Issue by mi-hol** [rusefi/rusefi_documentation#266]
Downloads are currently limited to 2 versions:
![image](https://user-images.githubusercontent.com/22799428/206933384-4b5acd2f-0d14-47d4-bfc0-c7db0d651dbf.png)

add link allowing for downloading history versions (i.e. for troubleshooting)

**Comment by rusefillc** [comment]
which exact page is affected? I see

![image](https://user-images.githubusercontent.com/48498823/206937915-2e77c818-8e86-4212-b614-aa87a61ca8d9.png)

**Comment by mi-hol** [comment]
https://github.com/rusefi/rusefi/releases?page=6 has oldest release [2017.03.31_release_1.0.2](https://github.com/rusefi/rusefi/releases/tag/2017.03.31_release_1.0.2)
SF has <html>
<body>


rusefi.r46.zip | 2013-10-20
-- | --



</body>
</html>[rusefi.r46.zip](https://sourceforge.net/projects/rusefi/files/rusefi.r46.zip/download)	2013-10-20
