### ISSUE TITLE
[Proposal] make "master" a protected branch to enforce update via PRs only 

### ISSUE THREAD

**Issue by mi-hol** [rusefi/rusefi_documentation#268]
I'd recommend to enforce certain workflows for "master" branch via "protection rules"- Possible "protection rules" such as requiring an approving review or passing status checks for all pull requests merged into the protected branch.
How to is documented in (https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule)

Background:
every member of doc-team has "merge" permission and can push to "master" branch unintentionally.

**Comment by mi-hol** [comment]
this change links nicely with #244

**Comment by mi-hol** [comment]
Andrey is fine with recommendation provided by doc-team

**Comment by chuckwagoncomputing** [comment]
I've already spoken to @mi-hol about this, but just so everyone is on the same page:
This will also mean disabling editing from https://github.com/rusefi/rusefi/wiki

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/212367438-0b772306-3b4a-411f-9f05-b051e9af8e88.png)

**Comment by rusefillc** [comment]
even with branch protection I can still make direct commits https://github.com/rusefi/rusefi_documentation/commit/a895791d0c4641f57a5641d7ad5bfd3ad56e603a

to be honest that works for me

**Comment by rusefillc** [comment]
> I've already spoken to @mi-hol about this, but just so everyone is on the same page: This will also mean disabling editing from https://github.com/rusefi/rusefi/wiki

at the moment exactly one person can edit https://github.com/rusefi/rusefi/wiki directly and that's me

please clarify the thought process here, what are we trying to solve how?

**Comment by chuckwagoncomputing** [comment]
As I understand it, the goal is to keep people from making bad commits that someone has to fix later.

Just to confirm, have you also selected "Require status checks to pass before merging"?

**Comment by rusefillc** [comment]
I did now

![image](https://user-images.githubusercontent.com/48498823/212422236-ca50326e-3380-44db-9f71-d9497b25295d.png)

**Comment by chuckwagoncomputing** [comment]
OK Thanks.

**Comment by mi-hol** [comment]
Thank you all, from my view this is a great process improvement!
