### ISSUE TITLE
Wiki3 navigation side bar expands towards bottom of topics, hides "Search"

### ISSUE THREAD

**Issue by mi-hol** [rusefi/rusefi_documentation#269]
Wiki3 navigation side bar jumps to section "Boards" without having scrollbar to move back to "Home" section
![image](https://user-images.githubusercontent.com/22799428/207379545-e1271a8f-a06e-4a50-b338-5dd91d01a8eb.png)

**Comment by chuckwagoncomputing** [comment]
https://github.com/mkdocs/mkdocs/issues/1904 Maybe relevant? I have commented.

**Comment by mi-hol** [comment]
seems like I can't fix this issue
