### ISSUE TITLE
multi-spark manual

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi_documentation#27]
we have mutli spark with zero content

**Comment by rusefi** [comment]
@mck1117 I would like to reiterate the importance of this ticket in my opinion.

**Comment by mck1117** [comment]
didn't @SVeilleux9 write a page on this?

**Comment by rusefi** [comment]
What is the URL for that page?

**Comment by OrchardPerformance** [comment]
I have put a template for the multi-spark into the last PR, @SVeilleux9 has some content to drop there. 
Otherwise I can take that over if required.

**Comment by SVeilleux9** [comment]
I have the document, I just need to pull together several TS screenshots and I can upload it.

**Comment by OrchardPerformance** [comment]
@SVeilleux9 - The page looks like it has had a lot of updates? 
Is this closed?

**Comment by rusefillc** [comment]
@mck1117 @SVeilleux9 ?

**Comment by SVeilleux9** [comment]
@OrchardPerformance Just a heads up I wrote that page without knowing much about multi-spark. I understand what it does, but it could probably use some wording as to why you would use it, why you should care.

**Comment by duhafnusa4** [comment]
We have https://github.com/rusefi/rusefi/wiki/Multi-Spark

Closing ticket

**Comment by rusefillc** [comment]
is feature list article linking at that page?

**Comment by duhafnusa4** [comment]
yes

https://github.com/rusefi/rusefi/wiki
