### ISSUE TITLE
Replace ts_generated with rusefi.com/online line

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#284]
rusefi.com/online is a superior way to show what TS screens we have since ts_generated is not invoked automatically and it's totally out of date

rusefi.com/online does a good enough job without any extra tool set

**Comment by mi-hol** [comment]
Too brief, doesn't ring a bell

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi_documentation/pull/281/files would be an example

I am saying that we shall remove /Overview/TS_generated and replace usages with something based on rusefi.online like https://rusefi.com/online/view.php?msq=1331&dialog=engineChars

**Comment by chuckwagoncomputing** [comment]
ts_generated is gone, should we close this?
