### ISSUE TITLE
Most or all of user-facing pages should not even be mentioning the console text commands

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#302]
Like https://github.com/rusefi/rusefi/wiki/Cranking https://github.com/rusefi/rusefi_documentation/commit/320ab6156190b321cb9fa452b0aeaeddc6c12b0b

**Comment by mi-hol** [comment]
Would you mind to mention the reasoning for this change?

In the example above I see no benefit as from the visual impression only "clutter" (actually distracting users), gets added via "More"
![image](https://user-images.githubusercontent.com/22799428/209474220-d7c9dcf8-f055-49d9-8ab4-93cf711c2786.png)

expands to:
![image](https://user-images.githubusercontent.com/22799428/209474262-e57f85b4-353a-4573-a360-b5815abd0eee.png)

**Comment by rusefillc** [comment]
Commands create wrong impressions that one has to be a software developer to operate the unit, we do not want that impression.

Commands are clearly noise for 99.9999% of the target audience

**Comment by mi-hol** [comment]
Now with a user base of 0.0001%, would the better approach be to remove the "noise" altogether?
