### ISSUE TITLE
232 links on wiki.rusefi.com to Hellen72 but no matching file

### ISSUE THREAD

**Issue by mi-hol** [rusefi/rusefi_documentation#307]
checked links using broken-link-checker
described [here](https://matthewsetter.com/writing-tools/npm-broken-link-checker/)
`blc https://wiki.rusefi.com -ro --exclude-external >.\wiki-tools\blc_20221224.log`
![image](https://user-images.githubusercontent.com/22799428/209442088-9808e4da-1587-4bf1-a855-db012cd82ecf.png)

output file: 
[blc_20221224.log](https://github.com/rusefi/rusefi_documentation/files/10298812/blc_20221224.log)

existing docu files are:
Hellen-WBO.md
Hellen-NB2.md

**Comment by mi-hol** [comment]
@andrei maybe you could shed light on this topic?

**Comment by mi-hol** [comment]
@BeerMoneyMotorsports maybe you could shed light on this topic?

**Comment by BeerMoneyMotorsports** [comment]
https://github.com/rusefi/rusefi/wiki/Hellen-NB2
