### ISSUE TITLE
EPIC: errors in markdown need fixing before merging a change (CI for documentation)

### ISSUE THREAD

**Issue by mi-hol** [rusefi/rusefi_documentation#308]
Validate Markdown Files With MarkdownLint according to [this ](https://matthewsetter.com/tools-that-make-technical-writing-easier-markdown-linter/)blog post revealed over 7K errors.
To avoid follow-on errors in other tools I'd suggest to fix them. 

Luckily most errors can be fixed automatically.

As a follow-up we should activate this check on each commit.
```
PS git\rusefi_documentation> markdownlint-cli2 "**/*.md" "#node_modules" 2>.\wiki-tools\mdl-20221224.log
markdownlint-cli2 v0.5.1 (markdownlint v0.26.2)
Finding: **/*.md !node_modules
Linting: 425 file(s)
Summary: 7557 error(s)
```
[mdl-20221224.log](https://github.com/rusefi/rusefi_documentation/files/10299257/mdl-20221224.log)

**Comment by mi-hol** [comment]
after PR #334 
markdownlint-cli2-config v0.5.1 (markdownlint v0.26.2)
Finding: **/*.md !node_modules
Linting: 424 file(s)
Summary: 4072 error(s)

**Comment by chuckwagoncomputing** [comment]
I've been working on this today. I've completed files starting with A-H.

**Comment by mi-hol** [comment]
@rusefillc sorry this is NOT closed
Again a case for #363

**Comment by chuckwagoncomputing** [comment]
You can't just re-open an issue without explaining why.

**Comment by mi-hol** [comment]
markdownlint-cli2 v0.6.0 (markdownlint v0.27.0)
Finding: **/*.md !node_modules
Linting: 426 file(s)
Summary: 3510 error(s)

**Comment by mi-hol** [comment]
@chuckwagoncomputing 
I must say that I find this a rather crappy approach!
![image](https://user-images.githubusercontent.com/22799428/211200279-180dc6d7-f9bb-417b-b67e-a2e0f06437b0.png)

**Comment by mi-hol** [comment]
to avoid misunderstanding I wanted to clarify:
I'm fine to provide a reason, the "crappy approach" is related to "back and forth" as explained further in #363 
ANY issue should be fixed completely, ofter multiple iterations are required to achieve that, because of different view points contributors have!

**Comment by chuckwagoncomputing** [comment]
Please state your view as to why this issue should not be closed.

**Comment by mi-hol** [comment]
"Documentation as Code" is a concept to apply CI to documentation in order to avoid common errors.
As a "kind of compiler" fpr md files several tools need to validate the content of a changed file and reject it for merging in case of detected errors & warning.

example:
![image](https://user-images.githubusercontent.com/22799428/212042174-1130c6a8-140f-4017-acbd-c8d0b2157a60.png)

**Comment by mi-hol** [comment]
Current implementation validates **all markdown files** but without any consequence in case of detected error

**Comment by chuckwagoncomputing** [comment]
Fixed. Details in #268

**Comment by mi-hol** [comment]
@chuckwagoncomputing does the current implementation prevent references with .md extension?
To my current understand this type of error was corrected manually and could re-occur any time unintentionally.

BTW: I Prefix this issue as "EPIC" (as suggested by Andrey) to remain in control of status

**Comment by chuckwagoncomputing** [comment]
No it doesn't. An idea I have for how to do that is to modify brokenlinks.sh to accept a flag to make it non-interactive, and just check links.

**Comment by mi-hol** [comment]
> modify brokenlinks.sh to accept a flag to make it non-interactive, and just check links.

  not sure if this is the best approach because in my tests [here ](https://wiki.rusefi.com/HOWTO-validate-links/) brokenlinks.sh was extremely slow compared to  markdown-link-validator.
As I understand it currently  markdown-link-validator is actually based on ESLint and consists of [just 49 lines of TypeScript code](https://github.com/webhintio/markdown-link-validator/blob/main/src/bin/markdown-link-validator.ts),
Do you happen to know TypeScript?

Another approach could be "[custom rule](https://github.com/DavidAnson/markdownlint/blob/main/doc/CustomRules.md)" for markdownlint.

**Comment by chuckwagoncomputing** [comment]
brokenlinks.sh takes less than a minute on my ~5 year old laptop. It could also be modified to only check the files that were changed in the PR.

If you really want to customize other tools to fit our needs, please feel free to do so. I only recommend not doing so because I don't feel that it's a good use of developer time.

**Comment by chuckwagoncomputing** [comment]
The same workflow would trigger whether a file was modified or files were renamed or deleted.
You could just check in the 'run' section, using some git command probably, if any files were renamed or deleted, and act accordingly.

Yes, I was wrong. I thought that the board was skipped if the id was missing, turns out the script says:
`# todo fail once all pages are compliant    exit 1`

**Comment by mi-hol** [comment]
close as script now fails if errors are detected
