### ISSUE TITLE
improve  workflow that uploads wiki2& wiki3  to handle testing and dir structure change

### ISSUE THREAD

**Issue by mi-hol** [rusefi/rusefi_documentation#309]
Current situation:

1. "workflow that uploads wiki3 overwrites without removing what already exists in order to not make the wiki go down temporarily." from https://github.com/rusefi/rusefi_documentation/issues/123#issuecomment-1364537056
2. "no test of changes possible" from #249
3. avoid automatic sync of wiki2 when pre-requisites are unmet (details in  https://github.com/rusefi/rusefi_documentation/pull/320#issuecomment-1368001890)

Desired situation:

1. all requirements are handled correctly
2. The new process is documented and reviewed before it's implemented

**Comment by chuckwagoncomputing** [comment]
This appears to be a strange collection of different issues, and I am confused.
1. Are you requesting a change in this behavior? If so, create an issue addressing it.
2. Solved with documentation
3. This is intended behavior - the workflow must fail if something is wrong. If you don't like getting the emails, you can disable the workflow in your repository.
