### ISSUE TITLE
embedded HTML code creates issues for MkDocs and results in wrong display on wiki.rusefi.com

### ISSUE THREAD

**Issue by mi-hol** [rusefi/rusefi_documentation#313]
## example:

![2022-12-27 17_51_39-List of FAQ and HOWTO pages - rusEFI Wiki - Vivaldi](https://user-images.githubusercontent.com/22799428/209699733-f08a0200-f095-42f5-8720-3faa7ec48b3a.png)

## root cause:
![2022-12-27 17_59_14-Pages-FAQ-and-HOWTO md - rusefi_documentation - Visual Studio Code](https://user-images.githubusercontent.com/22799428/209699767-ac76cc54-2e20-4210-bd94-e1576ee9f047.png)

## fix:
**use only markdown tags and remove embedded HTML code**

![image](https://user-images.githubusercontent.com/22799428/209699883-6e89c55b-567c-42d5-958b-14edf106363a.png)

![image](https://user-images.githubusercontent.com/22799428/209700292-b09d4524-d325-4412-8654-02c1d6f19ae0.png)

## affected markdown files

117 results - 8 files
```
FAQ-Ignition.md:
  42  
  43: <details><summary><u>I want to buy new coils</u></summary>
  44  


Pages-Fuel.md:
   2  
   3: <details><summary><u>rusEFI Project</u></summary>
   4  


Pages-HOWTO.md:
  2  
  3: <details><summary><u>HOW TO</u></summary>
  4  
...
Pages-Ignition.md:
   4  
   5: <details><summary><u>rusEFI Project</u></summary>
   6  
...

Pages-Sensors-and-Actuators.md:
   2  
   3: <details><summary><u>Throttle and ETB</u></summary>
   4  
...

Pages-Software.md:
   2  
   3: <details><summary><u>rusEFI Project</u></summary>
   4  
...

Vault-Of-Terminology.md:
    4  
    5: <details><summary><u>AAP</u></summary>
    6  
...
```

**Comment by chuckwagoncomputing** [comment]
details and summary tags work fine in Wiki3, but you have to add markdown parameters - see [Cranking.md](https://github.com/rusefi/rusefi_documentation/blob/master/Cranking.md) for example.

**Comment by mi-hol** [comment]
> details and summary tags work fine in Wiki3, but you have to add markdown parameters

This is really thin ice and from my view won't work reliably without proper documentation and tooling!
As we already see the negative impacts of not having that, a plan to get this back under control would be a starting point.
Anything to contribute?

**Comment by mi-hol** [comment]
documentation and tooling is missing, #318 only fixed "tip of iceberg"

**Comment by chuckwagoncomputing** [comment]
Documentation now exists in https://wiki.rusefi.com/HOWTO-contribute-to-documentation/
Do you have any ideas for checking this with tooling? Write our own linter? In my opinion, the effort required to write a linter is so much more than the effort for editors to check manually that their edits haven't created a broken details section, that it's not worth writing a linter.

**Comment by mi-hol** [comment]
> Do you have any ideas for checking this with tooling?

Do you happen to know https://github.com/DavidAnson/markdownlint-cli2?
Blog post https://dlaa.me/blog/post/markdownlintcli2 makes me optimistic it will fit with our requirements.

my decision factors are driven by benefits & reliability not only by efforts.

> editors to check manually

is unfortunately not an option to trust on because an editor with the only the best intent (like me) may introduce errors unintentionally due to lacking context, skill or requirements for a specific aspect.
What I learned is that there is never stability regarding contributors in a project team!
Meaning someone is always below the required skill level to work "error free".
Tooling is the only option to safeguard against this thread for a project.

**Comment by chuckwagoncomputing** [comment]
markdownlint doesn't come anywhere close to doing what we need without writing our own checks for it. I guess if somebody wants to do that, they can, but it seems to me like a poor use of developer time.

**Comment by mi-hol** [comment]
> markdownlint doesn't come anywhere close to doing what we need

Could you perhaps add what you know to be needed?

**Comment by mi-hol** [comment]
> markdownlint doesn't come anywhere close to doing what we need

did you check https://github.com/DavidAnson/markdownlint-cli2 as the tool I currently use?

**Comment by chuckwagoncomputing** [comment]
markdownlint only checks for presence of HTML.
We need HTML, with particular parameters for tags if there is markdown within them, and empty lines after particular closing tags. markdownlint doesn't know how to do any of that.

**Comment by chuckwagoncomputing** [comment]
If you want to modify markdownlint to do that, you may. If not, let's close this issue.

**Comment by mi-hol** [comment]
again #363 :(
This is my issue to deal with!
![image](https://user-images.githubusercontent.com/22799428/211203604-b5096a32-0a5a-4cdf-bebb-82922ba69233.png)

**Comment by mi-hol** [comment]
below approach is not what I envisaged

![image](https://user-images.githubusercontent.com/22799428/211203821-ce425fa5-ab81-4a16-8fcf-854b83f42f0d.png)

**Comment by chuckwagoncomputing** [comment]
Fixed. Details in #268
