### ISSUE TITLE
https://wiki.rusefi.com/Lua-Scripting/ formatting broken. 

### ISSUE THREAD

**Issue by mi-hol** [rusefi/rusefi_documentation#351]
Michael Holzer
  [3:48 PM](https://rusefi.slack.com/archives/CRNUACJ84/p1672930090428689)
what I find strange is that a commit to rusefi/rusefi has a direct impact to rusefi/[rusefi_documentation](https://github.com/rusefi/rusefi_documentation)  but in the source file https://wiki.rusefi.com/Lua-Scripting/ there is absolutely no hint about this been an auto-generated file!

nmschulte
  [3:48 PM](https://rusefi.slack.com/archives/CRNUACJ84/p1672930118197269)
well, it's in the name, but again this isn't clear to the uninitiated -- we can write language to clear that up
[3:49](https://rusefi.slack.com/archives/CRNUACJ84/p1672930147851449)
I'll put something together about this quick, but have to work in a handful -- just a min

Michael Holzer
  [3:51 PM](https://rusefi.slack.com/archives/CRNUACJ84/p1672930268249919)
BTW: formatting of https://wiki.rusefi.com/Lua-Scripting/ is broken
image.png
 
![image](https://user-images.githubusercontent.com/22799428/210809036-b080cf16-c3ba-4d49-81ee-ca34c2fb5ee1.png)

**Comment by nmschulte** [comment]
Working on some changes to provide clarity here, stand by.

**Comment by rusefillc** [comment]
https://wiki.rusefi.com/Lua-Scripting/ is not auto-generated

**Comment by mi-hol** [comment]
> https://wiki.rusefi.com/Lua-Scripting/ which is https://github.com/rusefi/rusefi_documentation/blob/master/Lua-Scripting.md is not auto-generated

Thanks for clarification, from Slack conversation, this was a wrong understanding then and rectifies concerns.

**Comment by chuckwagoncomputing** [comment]
I caused the `float: left` problem. I'll fix it.

**Comment by chuckwagoncomputing** [comment]
Seems to be fixed
