### ISSUE TITLE
more "overview" content

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi_documentation#36]
we need more content on 
https://github.com/rusefi/rusefi/wiki/overview

we shall take parts of https://rusefi.com/wiki/index.php?title=Main_Page at least embed some of youtube 

let's see if we can copy/paste anything from https://rusefi.com/forum/viewtopic.php?f=13&t=1658 presentation

**Comment by rusefi** [comment]
@duhafnusa4 can you look into this?

**Comment by duhafnusa4** [comment]
I'm on it

**Comment by duhafnusa4** [comment]
images for screenshots of video links
![rusEFI_1](https://user-images.githubusercontent.com/5051341/80620873-2bf5ef80-8a0c-11ea-80be-6a76a9c4a129.png)

**Comment by duhafnusa4** [comment]
updated to look better. We can add more if we want. 

![rusEFI_1](https://user-images.githubusercontent.com/5051341/80621997-bf7bf000-8a0d-11ea-998e-48fc3accba59.png)

**Comment by duhafnusa4** [comment]
![rusEFI_2](https://user-images.githubusercontent.com/5051341/80622501-809a6a00-8a0e-11ea-8efc-b575def1d132.png)

**Comment by duhafnusa4** [comment]
This page now has lots of good information. Closing ticket.
