### ISSUE TITLE
[process proposal] peer review

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#379]
@mi-hol please do not self-merge PRs right away, please allow someone else on the team to review and merge

https://github.com/rusefi/rusefi_documentation/pull/378 is an example of the approach which I believe we should adjust

**Comment by mi-hol** [comment]
@rusefillc the existing "[Proposal] make "master" a protected branch to enforce update via PRs only " #268 is from my view the solution to establish a defined workflow including peer review that will work independent of contributor's process knowledge.

At this stage the desired workflow seems not documented, please correct me in case I got this wrong.

To activate the setting "make "master" a protected branch "
could you please grant @chuckwagoncomputing "admin" role for rusefi/rusefi_documentation  via settings/ Access ?
GitHub documentation for this topic is [here](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-an-individuals-access-to-an-organization-repository)

![image](https://user-images.githubusercontent.com/22799428/212353591-3ef1674b-bdce-4d71-a1bc-d6496ea3a3e5.png)

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi_documentation master branch is now protected
