### ISSUE TITLE
dead links - toolset and audit

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi_documentation#38]
we have a few broken links even image links on the new wiki

we need to document our favorite online or offline took to find broken links

we shall see what's the status with broken link and what can we fix

**Comment by rusefi** [comment]
@Timbelom can you google what are helpful tools here?

**Comment by OrchardPerformance** [comment]
My favorite offline link detection method is @GlitchKnitter

**Comment by rusefi** [comment]
@OrchardPerformance is that Artificial Intelligence or Natural Intelligence System?

**Comment by chuckwagoncomputing** [comment]
I have created a tool:
https://github.com/rusefi/rusefi_documentation/blob/master/wiki-tools/brokenlinks.sh

I have created an issue with the remaining links that is has found that cannot be fixed automatically by it:
https://github.com/rusefi/rusefi_documentation/issues/123
