### ISSUE TITLE
improve link validation in md files (include http links)

### ISSUE THREAD

**Issue by mi-hol** [rusefi/rusefi_documentation#389]
All md files in this repository contain over 3500 links.
Validation of a single link with current shell script ./wiki-tools/brokenlinks.sh requires about 3.5 seconds on my I5 Gen2 laptop in WSL Ubuntu 22.04 environment (see example run from a slightly modified version of this script below).

Total elapsed time for a complete verification run for all md files  is therefore over 3.5 hours.

Conclusion: 
Not really feasible to run it therefore on personal laptop

Question:

- Is it run as part of doc build process?
- In case of detected issues, is the output sent to someone to take corrective actions?

```bash
mholzer@PB6460b-DE:/mnt/c/Users/mholzer/Documents/git/rusefi_documentation$ ./wiki-tools/brokenlinks.sh
++ date
+ printf '%s\n' 'Tue Jan 17 13:30:44 CET 2023:script started'
Tue Jan 17 13:30:44 CET 2023:script started
+ export -f escape
+ export -f escapeReplace
+ export -f searchfile
++ date
+ printf '%s\n' 'Tue Jan 17 13:30:44 CET 2023'
Tue Jan 17 13:30:44 CET 2023
+ find . -iname '*.md' -exec bash -c 'searchfile "$0"' '{}' ';'
Tue Jan 17 13:30:46 CET 2023:link:'OEM-Docs/Mitsubishi/1995-3000gt-1.png'
Tue Jan 17 13:30:50 CET 2023:link:'OEM-Docs/Mitsubishi/1995-3000gt-2.png'
Tue Jan 17 13:30:54 CET 2023:link:'OEM-Docs/Mitsubishi/1995-3000gt-3.png'
Tue Jan 17 13:30:57 CET 2023:link:'OEM-Docs/Mitsubishi/1995-3000gt-charging.png'
Tue Jan 17 13:31:01 CET 2023:link:'OEM-Docs/Mitsubishi/1995-3000gt-starting-without-theft.png'
Tue Jan 17 13:31:05 CET 2023:link:'OEM-Docs/Mitsubishi/1995-3000gt-starting-with-theft.png'
Tue Jan 17 13:31:08 CET 2023:link:'OEM-Docs/Mercedes/1997-e320-1.png'
Tue Jan 17 13:31:12 CET 2023:link:'OEM-Docs/Mercedes/1997-e320-2.png'
Tue Jan 17 13:31:15 CET 2023:link:'OEM-Docs/Mercedes/1997-e320-3.png'
Tue Jan 17 13:31:19 CET 2023:link:'OEM-Docs/Mercedes/mercedes_170.png'
Tue Jan 17 13:31:22 CET 2023:link:'https://en.wikipedia.org/wiki/Mercedes-Benz_M112_engine'
Tue Jan 17 13:31:22 CET 2023:link:'OEM-Docs/Mercedes/99_e320_1.png'
Tue Jan 17 13:31:26 CET 2023:link:'OEM-Docs/Mercedes/99_e320_2.png'
Tue Jan 17 13:31:30 CET 2023:link:'OEM-Docs/Mercedes/99_e320_3.png'
Tue Jan 17 13:31:33 CET 2023:link:'OEM-Docs/Mercedes/mercedes_170.png'
Tue Jan 17 13:31:37 CET 2023:link:'https://en.wikipedia.org/wiki/Mercedes-Benz_M113_engine'
Tue Jan 17 13:31:37 CET 2023:link:'OEM-Docs/Mercedes/1999_e430_page_1.png'
Tue Jan 17 13:31:40 CET 2023:link:'OEM-Docs/Mercedes/1999_e430_page_2.png'
Tue Jan 17 13:31:43 CET 2023:link:'OEM-Docs/Mercedes/1999_e430_page_3.png'
Tue Jan 17 13:31:47 CET 2023:link:'OEM-Docs/Mercedes/mercedes_170.png'
^C
```

modified version of script
```
#!/usr/bin/env bash
##################################################################################################
#                                         brokenlinks.sh                                         #
#                                           02/18/2021                                           #
#                                   Written By David Holdeman                                    #
#     Searches for broken links in a Github Wiki repo, and suggests and applies corrections.     #
##################################################################################################
# to echo all shell commands called and expand any variable name
set -o xtrace
printf '%s\n' "$(date):script started"
# These two functions are used to escape variables for use in a sed command
# Passed a single string
escape() {
  sed 's/[^^]/[&]/g; s/\^/\\^/g' <<<"$1";
}
export -f escape
escapeReplace() {
  sed 's/[&/\]/\\&/g' <<<"$1";
}
export -f escapeReplace

# Main processing function
# Passed the path to a .md file
searchfile() {
  # This loops for every link in the file.
  # See the end of the function for the grep that finds the links in the file.
  # We use file descriptor 3, because if we used stdin, the read calls inside this loop would read from that instead of
  #  reading the user's input.
  while IFS= read -r -u 3 link; do
    printf '%s\n' "$(date):link:'$link'"
    # If it's an internet link, ignore it.
    # That's beyond the scope of this tool.
    if echo $link | grep -E '^[http|\/]' >/dev/null; then
      continue
    fi
    # At some point in this scripts development, fixed links to files/images were given the './' prefix.
    # This didn't really hurt anything, but it's not idiomatic.
    # I added this to fix the problems I caused, and decided it was worth keeping around.
    if echo $link | grep -E '^\./' >/dev/null; then
      # NEWLINK is the corrected link
      NEWLINK=$(echo $link | sed 's/^\.\///')
      # Print the file and the old link
      echo "In $1:"
      echo $link
      # Print the options as though they are a list in order to have the same UI as other types of correction
      echo $NEWLINK | cat --number
      # Read the user input
      read PICK
      if [ $PICK -eq 1 ]; then
        # Replace the old link with the new one.
        # Parentheses are placed around both the old link and new one in order to ensure we replace the link,
        #   and not some other place in the file that happens to use the same words.
        REPLACE=$(escape '('"$link"')')
        REPLACEWITH=$(escapeReplace "$NEWLINK")
        sed -i "s/$REPLACE/\($REPLACEWITH\)/" "$1"
      fi
      # We don't continue here because the link we fixed might be broken.
    fi
    # Skip links that are to an .md file and aren't broken.
    if [ "$(find . -name "$link"".md" 2>/dev/null | wc -l)" -gt 0 ]; then
      continue
    fi
    # Skip links that are to a hash fragment.
    if echo "$link" | grep "#" >/dev/null; then
      continue
    fi
    # Process links that are not to an .md file.
    # We need to do this separately because Github/gollum behave differently with different kinds of links.
    # .md files need the name of the file, without the .md extension.
    # Everything else needs the path relative to the repo root.
    if echo "$link" | grep -Ev ".md$" >/dev/null; then
      # Skip the link if it's not broken.
      if ls "$link" 2>/dev/null >/dev/null; then
        continue
      fi
      # Print the filename and the broken link.
      echo "In $1:"
      echo $link
      # Build the search term we will look for.
      # All hyphens and underscores are replaced with asterisks, so we
      #   can find files with mismatched hyphens or underscores.
      SEARCH='*'$(basename "$link" | sed 's/[-_ ]/*/g')'*'
      # Search for matching files.
      FILES=$(find . -iname "$SEARCH")
      # If there are no files, skip to next link.
      if [ "$(echo -n "$FILES" | wc -c)" -lt 1 ]; then
        echo "Could not find"
        continue
      fi
      # List the potential files, with numbers.
      echo "$FILES" | cat --number
      # Read the user input
      read PICK
      # If the selection isn't a number, skip to the next link.
      if ! [[ $PICK =~ ^[0-9]+$ ]]; then
        continue
      fi
      # Get the selected file path, without the preceding ./
      FILE=$(echo "$FILES" | head -n $PICK | tail -n 1 | sed 's/^\.\///')
      # Replace the old link with the new one.
      # Parentheses are placed around both the old link and new one in order to ensure we replace the link,
      #   and not some other place in the file that happens to use the same words.
      REPLACE=$(escape '('"$link"')')
      REPLACEWITH=$(escapeReplace "$(basename "$FILE" .md)")
      sed -i "s/$REPLACE/\($REPLACEWITH\)/" "$1"
      continue
    fi
    echo "In $1:"
    echo $link
    # Build the search term we will look for.
    # All hyphens and underscores are replaced with asterisks, so we
    #   can find files with mismatched hyphens or underscores.
    SEARCH='*'$(basename "$link" | sed 's/[-_ ]/*/g')'*'
    # Search for matching files.
    FILES=$(find . -iname "$SEARCH")
    # If there are no files, skip to next link.
    if [ "$(echo -n "$FILES" | wc -c)" -lt 1 ]; then
      echo "Could not find"
      continue
    fi
    # List the potential files, with numbers.
    echo "$FILES" | cat --number
    # Read the user input
    read PICK
    # If the selection isn't a number, skip to the next link.
    if ! [[ $PICK =~ ^[0-9]+$ ]]; then
      continue
    fi
    # Get the selected file path, without the preceding ./
    FILE=$(basename "$(echo "$FILES" | head -n $PICK | tail -n 1)" .md)
    # Replace the old link with the new one.
    # Parentheses are placed around both the old link and new one in order to ensure we replace the link,
    #   and not some other place in the file that happens to use the same words.
    REPLACE=$(escape '('$link')')
    REPLACEWITH=$(escapeReplace "$FILE")
    sed -i "s/$REPLACE/\($REPLACEWITH\)/" "$1"
  # This regex finds links in the file that is passed to searchfile
  # Results are fed to file descriptor 3 for the reasons previously explained.
  done 3< <(grep -oP '(?<=\]\().*?(?=[\)])' "$1" | sed -e "s/^<//g" -e "s/>$//g" | cut -d '"' -f1 | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
}
export -f searchfile

# run searchfile on every .md file in the repo
printf '%s\n' "$(date)"
find . -iname "*.md" -exec bash -c 'searchfile "$0"' {} \;
printf '%s\n' "$(date):script ended"
```

**Comment by chuckwagoncomputing** [comment]
On my laptop with i7-8550U, SATA SSD, and 16GB of RAM, it takes 1 minute 8 seconds. I previously said it took less than a minute, but I guess my internal clock is a little off. :)

**Comment by chuckwagoncomputing** [comment]
@mi-hol I have done some magic that I suspect won't actually help you much.
Try https://github.com/chuckwagoncomputing/rusefi_documentation/blob/26497419162c9f179ecb4c0e67d5040a335f06af/wiki-tools/brokenlinks.sh
It will print the time of every link checked, so we know how long each takes.

On my laptop it now takes about 15 seconds.

**Comment by chuckwagoncomputing** [comment]
Further, you can try
https://github.com/chuckwagoncomputing/rusefi_documentation/blob/1b72ad1e2ac0d612b547c72b152575411cce65b5/wiki-tools/brokenlinks.sh
Which cuts the time down to 11 seconds on my laptop.

**Comment by chuckwagoncomputing** [comment]
For the fun of it, I tried on my AMD 3400G desktop, and got ~7.3 seconds. I tried copying it to a PCIE gen 3 NVME SSD, and it only improved slightly to ~7.15.
I need to build a faster computer to run my bash scripts faster.

**Comment by mi-hol** [comment]
slow performance is likely caused WSL2 being a VM and my old I5 Gen 2 processor

Validating OEM-connectors.md requires 49s

 ./wiki-tools/brokenlinks_test.sh OEM-connectors.md
11:46:38.783477062
11:46:38.794936063
11:46:38.804095863
11:46:38.814390964
11:46:38.825034565
11:46:38.835364066
11:46:38.847255666
11:46:38.857783267
11:46:38.867884568
11:46:38.878546469
11:46:38.888932870
11:46:38.899763170
11:46:38.910647871
11:46:38.922003372
11:46:38.932323973
11:46:38.944181374
11:46:40.772543110
.....
11:47:23.932571341
11:47:25.516969406
11:47:25.529392108
11:47:25.541780210
11:47:25.556097512
11:47:25.570733315
11:47:25.585222417
11:47:27.369675815
11:47:27.382045717
11:47:27.394159819

**Comment by chuckwagoncomputing** [comment]
I've done as much as I can with brokenlinks.sh.
If you want to continue further with other solutions, I will leave this open.

**Comment by mi-hol** [comment]
mholzer@PB6460b-DE:/mnt/c/Users/mholzer/Documents/git/rusefi_documentation$ ./wiki-tools/brokenlinks.sh
(34secs)
mholzer@PB6460b-DE:/mnt/c/Users/mholzer/Documents/git/rusefi_documentation$ ./wiki-tools/brokenlinks.sh *.md
  (3secs)
above commands finish in less than 1 minute now, but what did they do?
Not indication given

**Comment by chuckwagoncomputing** [comment]
> mholzer@PB6460b-DE:/mnt/c/Users/mholzer/Documents/git/rusefi_documentation$ ./wiki-tools/brokenlinks.sh *.md
(3secs)

If that finished in 3 seconds there is almost certainly a bug. I'll take a look when I get home from work today.

**Comment by chuckwagoncomputing** [comment]
_Sidebar.md and _Footer.md are specific to Github Wiki, and due to the brokenness of Github Wiki, contain links that are "broken" if interpreted within the context of Wiki3 (or even other pages on Wiki2!)

brokenlinks.sh knows to exclude these files if you run it without passing it any files, but if you want to pass a list of all .md files to it, you will have to exclude those. There's a way to do that in bash, I've almost never used it, and don't remember how, but the relevant doc is https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Pattern-Matching

**Comment by mi-hol** [comment]
@chuckwagoncomputing I'd like to prevent image URL links to "https://user-images.githubusercontent.com/" and IMGUR hoster.

Is the correct place to add this code to be added in brokenlinks.sh function checkurl or is there a better solution?

**Comment by rusefillc** [comment]
@chuckwagoncomputing I'd like to keep image URL links to "https://user-images.githubusercontent.com/"

**Comment by chuckwagoncomputing** [comment]
Yep, that's a good place. The check for HTTP links is on [line 30](https://github.com/rusefi/rusefi_documentation/blob/e934c888bd2eb738f0247f7a5ac425dd6b1c5f98/wiki-tools/brokenlinks.sh#L30).

**Comment by mi-hol** [comment]
> @chuckwagoncomputing I'd like to keep image URL links to "https://user-images.githubusercontent.com/"

@rusefillc keeping this will have negative impacts for:
https://github.com/rusefi/rusefi_documentation/issues/459
https://github.com/rusefi/rusefi_documentation/issues/1
https://github.com/rusefi/rusefi_documentation/issues/431

in the long run as the repo is no longer in control of the full content used!

This has a very big impact therefore and should not be decided lightly!

**Comment by rusefillc** [comment]
@mi-hol so we have a case of "humans want one things, machine wants something else". Meaning that more automation is needed to automatically convert one-paste-click images from user-images into Images/

**Comment by mi-hol** [comment]
@rusefillc would you please let me know how automation could create a meaningful and correct name from the currently available information like below, I'd be happy to implement it.
this the available info for automation:
`![image](https://user-images.githubusercontent.com/17059674/177897778-0f450933-71eb-48d5-97cb-81741f11061e.png)`

**Comment by rusefillc** [comment]
@mi-hol might be saying that with extra effort we get readable names if we go fully manual image add

I am saying that better image names are not always worth the effort

While we can have automation to suck such github clipboard images into repo I am not sure why
