### ISSUE TITLE
Update rusEfi map & mention map on wiki

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi_documentation#39]
jvluntzel now has access to edit rusEfi map

it could be that https://rusefi.com/forum/viewtopic.php?p=31825#p31825 is the last update I did? 

once we update we shall post on the forum "everyone added" for us to know where is the threshold for next time

**Comment by duhafnusa4** [comment]
@rusefillc its been a long time since i logged in. Can you remind me how? I will update after.

**Comment by duhafnusa4** [comment]
Map has been updated. We should set how often we want to update the list, and I will add that to my calendar to perform. Then we can close this ticket.

**Comment by chuckwagoncomputing** [comment]
For some reason I'm not showing up on the map in the first message on the forum. I checked a few other people who joined recently and they're missing too.

**Comment by duhafnusa4** [comment]
So..do we really care about the map?

**Comment by rusefillc** [comment]
Not really
