### ISSUE TITLE
Add microRusEfi documentation to index page

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi_documentation#40]
We need a reference to MRE documentation on wiki home.md

MRE documentation itself is a mess with 70% on RE wiki and 30% on microRusEfi github

https://github.com/rusefi/hw_microRusEfi/wiki is the cherry on the cake

**Comment by rusefi** [comment]
@duhafnusa4 can you?

**Comment by duhafnusa4** [comment]
@rusefi do I need to fork to edit wiki home.md? sorry still learning the ins and outs of GH

**Comment by duhafnusa4** [comment]
![MRE_PCB](https://user-images.githubusercontent.com/5051341/80747087-806e9d00-8ae8-11ea-983e-330dfc6e3015.jpg)
![MRE_CASE](https://user-images.githubusercontent.com/5051341/80747096-849aba80-8ae8-11ea-862c-d124ef75f06a.jpg)

**Comment by rusefi** [comment]
@OrchardPerformance close or not close?

**Comment by duhafnusa4** [comment]
https://github.com/rusefi/rusefi/wiki/Hardware-microRusEFI is the page for MRE documentation now. Closing ticket.
