### ISSUE TITLE
replace or delete corrupted pdf files

### ISSUE THREAD

**Issue by mi-hol** [rusefi/rusefi_documentation#402]
the following pdf file can't be opened.

/OEM-Docs/Polaris/2015\ RZR\ 900\ Service-Manual-two-pages.pdf
/OEM-Docs/VAG/2006-Passat-B6/5-4420.01-41W038_PQ35-0-FRM-DE-P\ VAG\ MED9.1\ TFSI.pdf

@rusefi/doc-team 
Has someone the correct files?

Otherwise they should be deleted

**Comment by rusefillc** [comment]
thank you! one file removed, one file replaced with a legit copy

**Comment by mi-hol** [comment]
fixed via https://github.com/mi-hol/rusefi_documentation/commit/8e8e84fc9960f3dadaf1aa8890ce7ee90ae9288b

**Comment by mi-hol** [comment]
weird that closing is allowed twice. Had issue open and page not refreshed before status update
