### ISSUE TITLE
make rusEFI shopping consistent

### ISSUE THREAD

**Issue by mi-hol** [rusefi/rusefi_documentation#406]
Currently several URL targets are used, leading to confusion

```
[rusEFI store](https://www.shop.rusefi.com/shop) seems the only correct one
```
incorrect seem to be:
```
[<https://www.tindie.com/stores/russian/> our store]

[Ebay Store](https://www.ebay.com/itm/333532119947)
[eBay Store](http://www.ebay.com/usr/rusefi)
```

To fix the links I need above findings confirmed

**Comment by mi-hol** [comment]
> https://www.tindie.com/stores/russian/ yes totally incorrect

would recommend a cleanup there
![image](https://user-images.githubusercontent.com/22799428/215841377-f3b9b75d-f03d-45c3-a329-14c60ef78333.png)

**Comment by mi-hol** [comment]
as it contradicts with #259 and creates a very inconsistent "shopping" experience regarding prices
![image](https://user-images.githubusercontent.com/22799428/216331512-8f74576e-35dd-4f51-9657-0aa701f103cb.png)

**Comment by rusefillc** [comment]
retired all duplicates https://www.tindie.com/stores/russian/
