### ISSUE TITLE
slack doc

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi_documentation#41]
we have a forum post explaining how to join slack but it's forum and confusing

we need Slack.md

**Comment by rusefi** [comment]
@Timbelom can you take care of this one?

forum post https://rusefi.com/forum/viewtopic.php?f=13&t=1198

**Comment by Timbelom** [comment]
@rusefi issue resolved

**Comment by rusefi** [comment]
@Timbelom please add to home.md maybe just edit homr.md online right in live wiki
