### ISSUE TITLE
requirement to manually sync navigation bar on wiki3 und wiki2 results in inconsistencies

### ISSUE THREAD

**Issue by mi-hol** [rusefi/rusefi_documentation#411]
Could the manual process be replaced with automation to avoid this source of error leading to inconsistencies?

i.e. use wiki3 [mkdocs.yaml](https://github.com/rusefi/rusefi_documentation/blob/master/mkdocs/mkdocs.yaml) 
  to create wiki2 [_Sidebar.md](https://github.com/rusefi/rusefi_documentation/blob/master/_Sidebar.md)

example of missed requirement is in https://github.com/rusefi/rusefi_documentation/pull/408

**Comment by chuckwagoncomputing** [comment]
Maybe, but it would be a bit of a mess.
You'd have a workflow that committed back to the repo, which would trigger the sync-wiki3 workflow again.
I don't think that would really be a problem, but it's an inelegant solution to a small problem.

**Comment by mi-hol** [comment]
manual edit in Wiki3 required for "boards" section to match wiki2
![image](https://user-images.githubusercontent.com/22799428/224053843-92d0b1fc-29b2-4c69-baf2-4dcc94438824.png)

**Comment by mi-hol** [comment]
address via https://github.com/rusefi/rusefi_documentation/pull/439

**Comment by mi-hol** [comment]
@rusefillc navigation on Wiki3 misses some Plug&Play boards, should they be added?

wiki2:
![image](https://user-images.githubusercontent.com/22799428/224060534-13cf3c3a-61e6-401d-8bba-3a817cf6e8f6.png)

wiki3:
![image](https://user-images.githubusercontent.com/22799428/224060889-ebddf53b-490f-4ed8-9ab1-6bf3eb3cec17.png)

**Comment by mi-hol** [comment]
well I'm only interested to fix a content inconsistency.
Currently  in Wiki3 (showing 2 Miata models) vs Wiki2 (showing 4 Miata models).
Wiki2 is usually considered the "master" therefore the 2 missing models should be added to Wiki3.

**Comment by mi-hol** [comment]
removing myself as my hands are tied without support
