### ISSUE TITLE
implement a workflow that implements "automatic aging of issues and pull requests".

### ISSUE THREAD

**Issue by mi-hol** [rusefi/rusefi_documentation#419]
https://github.com/actions/stale is available to start with.

Specification of intended behavior:

- assign label "staled" to  issue or PR after 30 days following below definition and add comment explaining next action and timeline
 *  Definition of rules:

1.  * skip items with label "backlog" or "next-iteration"

- close all items labeled  with "staled"   after 60 days since being labeled.
- separate workflow code for "assign label" and "close based on label" to allow for:
  * gradual activation of workflows
  * intentional time delay between the different actions for QA/corrective actions

This means: 
- items can be exempted from "close based on label" by removing the label manually!
- just adding a comment will NOT clear the label "staled"

**Comment by chuckwagoncomputing** [comment]
This is very different to what @rusefillc specified [here](https://github.com/rusefi/rusefi_documentation/issues/418#issuecomment-1429767252).

**Comment by mi-hol** [comment]
I know but:
1. the requirement was extremely vague 
2. from experience I know that workflow require labels to work correctly
I've added the label "feedback requested" to give others a chance to comment and have added from your feedback "not planned" to signal that it's not ready for implementation yet.
