### ISSUE TITLE
Document rusEFI platforms and channels guidelines

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi_documentation#42]
from phone calls to facebook group we shall list all channels on one wiki page and articulate our strategy

**Comment by rusefi** [comment]
@OrchardPerformance ?

**Comment by rusefi** [comment]
@OrchardPerformance

**Comment by OrchardPerformance** [comment]
Will put this on the (literal physical post-it not on my monitor) list

**Comment by duhafnusa4** [comment]
This information is displayed on the sidebar in https://github.com/rusefi/rusefi/wiki.

Has the following:

**Community**
- Forum
- Slack
- Facebook Users Group
- Engines running on rusEFI
- HOWTO-help-rusEFI
