### ISSUE TITLE
should "rusefi/firmware/tunerstudio/docs/readme.MD" be moved to doc repo?

### ISSUE THREAD

**Issue by mi-hol** [rusefi/rusefi_documentation#421]
Several questions related to TunerStudio docs

1. should "rusefi/firmware/tunerstudio/docs/readme.MD" be moved to doc repo?
2. current reference "![TS](0 - 2 Tuning menu (2-47).png)" does not draw correctly. Reason unclear, but maybe file name containing  blanks & special chars
3. "Tuner Studio dialogs as of May 2017" could the pictures be refreshed and file names without blanks & special chars be used?

**Comment by rusefillc** [comment]
so much stuff piles together :(


please create individual tickets with https://xyproblem.info/
I have no motivation to move files since I see no explanation of why such actions would benefit who

**Comment by mi-hol** [comment]
Fact:
there is a pile of obsolete and unmaintained docs scattered over many places

Problem:
Users are confused on state of rusEFI and its capabilities. Leading to potential new user to choose instead another solution.
Cleanup activities are blocked instead of getting supported (see https://github.com/rusefi/rusefi_documentation/pull/404)

**Comment by rusefillc** [comment]
Fact: i ask you be to less vague and you go more vague :)

**Comment by rusefillc** [comment]
See https://github.com/rusefi/rusefi/commit/946b31296a6abb899ddaa9fee21951f5af015400 for my thoughts on this

PS: @mi-hol in my opinion we are facing negative consequence of your choice to make a shortcut and put more stress on me.

In my opinion higher quality ticket would have explicit https://github.com/rusefi/rusefi/tree/master/firmware/tunerstudio/docs URL

**Comment by mi-hol** [comment]
blocked until https://github.com/rusefi/rusefi_documentation/issues/423 is closed

**Comment by mi-hol** [comment]
not feasible
