### ISSUE TITLE
trigger page should be converted from numeric file names to full file names

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#422]
https://raw.githubusercontent.com/rusefi/rusefi_documentation/master/All-Supported-Triggers.md has both legacy ``Images/triggers/trigger_49.png`` and newer ``Images/triggers/trigger_TT_SUBARU_EZ30.png`` references

we shall migrate all references to full file names and remove all files with numbers from https://github.com/rusefi/rusefi_documentation/tree/master/Images/triggers

See https://github.com/rusefi/rusefi/blob/master/firmware/controllers/algo/engine_types.h#L309 for number to name conversion

**Comment by rusefillc** [comment]
@mi-hol can you please help?

**Comment by mi-hol** [comment]
@rusefillc in case we can resolve #421 with an agreement, yes

**Comment by rusefillc** [comment]
Grrrrrrrrrrrr :(

**Comment by mi-hol** [comment]
@rusefillc should the same picture be referenced more than once?
Current example:
![image](https://user-images.githubusercontent.com/22799428/220319520-21bad118-d1f4-4d2f-86fc-8a55baad3c68.png)
