### ISSUE TITLE
grant rusefi/doc-team read access to rusEFI forum to enable doc URL link checks

### ISSUE THREAD

**Issue by mi-hol** [rusefi/rusefi_documentation#423]
initial test with user mi-hol

**Comment by mi-hol** [comment]
@rusefillc may I kindly remind you of this blocking task to grant me read access to rusEFI forum?

**Comment by rusefillc** [comment]
Yes it's on the list :( My bad

**Comment by mi-hol** [comment]
this is blocking research for https://github.com/rusefi/rusefi_documentation/issues/255 too

**Comment by rusefillc** [comment]
@mi-hol status update: I do not see a trivial way to add a read-only user. something is off, at the moment it looks like I only have one user for the database that's odd but that's how it looks like

**Comment by mi-hol** [comment]
if you'd tell me the DBMS used for forum I'd be happy to provide the SQL statements to add a read-only group and add user(s) to it

**Comment by rusefillc** [comment]
phpbb 3.2.11
MySQL 5.7

**Comment by mi-hol** [comment]
tried to get support from Andrey (who is the only person with access to forum database) via SLACK messages, but no progress since 13Apr2023
