### ISSUE TITLE
BUILD: png images could be reduced in size on avg by 15% using oxipng

### ISSUE THREAD

**Issue by mi-hol** [rusefi/rusefi_documentation#431]
oxipng available from[ shssoichiro/oxipng](https://github.com/shssoichiro/oxipng#installing)
would reduce size of current png images on avg by 15% and as result would speed up loading of wiki pages by same percentage.

@chuckwagoncomputing Does it make sense to add  oxipng to build task?

Test results achieved via recommended options `"C:\Program Files\oxipng\oxipng.exe" -o 4 -i 1 --strip safe *.png`

original size of Images directory:

![2023-03-06 13_05_18-Images Properties](https://user-images.githubusercontent.com/22799428/223109199-ed7f2a4b-a640-46c2-a9fe-d6b5ace63b1f.png)

reduced size of Images directory:

![2023-03-06 13_11_22-Images Properties](https://user-images.githubusercontent.com/22799428/223109299-e4e70977-30cf-47d7-a788-91f16d54c9ea.png)

**Comment by chuckwagoncomputing** [comment]
If it's really lossless, it makes more sense to run it once.

**Comment by mi-hol** [comment]
with running only once, updates & additions wont benefit. 
Maybe instead of "build" I should write on PR validation?
