### ISSUE TITLE
Note: https://www.ebay.com/itm/334140404909 has a typo in title "encosure" instead of "enclosure"

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#434]
Note: https://www.ebay.com/itm/334140404909 has a typo in title "encosure" instead of "enclosure"

**Comment by Timbelom** [comment]
What? No mention of "encosure" on the entire listing

**Comment by rusefillc** [comment]
it must be before the massive update

![image](https://user-images.githubusercontent.com/48498823/227063959-86bc9396-7c9b-4157-bcaf-3ebfcee41a81.png)
