### ISSUE TITLE
EPIC: Evolve WIKI into a structured reference doc to cope with requirements of professional workshops

### ISSUE THREAD

**Issue by mi-hol** [rusefi/rusefi_documentation#459]
- remove obsolete content
  - example: Debug-Mode (see https://github.com/rusefi/rusefi/issues/3614#issuecomment-1354347339) 
- structure content along a "red line to follow"
  - good example: https://speeduino.com/Speeduino_manual.pdf

**Comment by rusefillc** [comment]
Yes please!

**Comment by mi-hol** [comment]
Plan is to use [Dev-Status.md](https://github.com/rusefi/rusefi_documentation/blob/master/Dev-Status.md) as the table-of-contents (TOC) for rusEFI features

**Comment by mi-hol** [comment]
wot be feasible
