### ISSUE TITLE
action "generate" in fork always aborts in step "upload pinouts"

### ISSUE THREAD

**Issue by mi-hol** [rusefi/rusefi_documentation#492]
Is below abort caused by a missing setting in forked repo or is logic for forked repo required in action definition?
Storing output of build in local repo fork or separate location from official destination would be great for validation purposes.
Maybe a good example is [this](https://github.com/FOME-Tech/wiki/blob/master/.github/workflows/deploy.yml)

![image](https://github.com/rusefi/rusefi_documentation/assets/22799428/7cfd88dd-5fff-4419-ae61-fef98a60dbbd)

**Comment by rusefillc** [comment]
Both.

Ideally actions would be smart enough to detect a fork and not attempt to upload

@chuckwagoncomputing any change to get you involved?
