### ISSUE TITLE
Need help on trigger setup

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi_documentation#59]
Looks like we need wiki pages related to how you setup most common triggers

See https://rusefi.com/forum/viewtopic.php?f=4&t=1759

**Comment by rusefi** [comment]
![image](https://user-images.githubusercontent.com/7377949/83332142-8da5b580-a267-11ea-95df-99b21aae924c.png)

![image](https://user-images.githubusercontent.com/7377949/83332150-98f8e100-a267-11ea-93cf-4f3f2b20840b.png)

**Comment by duhafnusa4** [comment]
Looks like these pages handle trigger setup

https://github.com/rusefi/rusefi/wiki/Trigger-Configuration-Guide

https://github.com/rusefi/rusefi/wiki/How-Do-I-Set-My-Trigger-Offset

@rusefillc if you approve I will close ticket

**Comment by mi-hol** [comment]
@rusefillc should this be closed?

**Comment by rusefillc** [comment]
That dialog has been since simplified a lot, closing.
