### ISSUE TITLE
Document verbose CAN mode

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi_documentation#69]
We have no docs for what data comes out on what channels, which would be useful for people with telemetry systems and dashboards.

**Comment by duhafnusa4** [comment]
@mck1117 I know I am assigned but I have no idea what to do lol

**Comment by mi-hol** [comment]
@rusefillc what is the priority and who could create the content?

**Comment by rusefillc** [comment]
We now have https://github.com/rusefi/rusefi/wiki/CAN which points at DBC file
