### ISSUE TITLE
TPS acceleration content move from legacy to new wiki

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#74]
@stefanst has contributes great content to https://rusefi.com/wiki/index.php?title=Manual:Software:Fuel_Control which would need to be moved to https://github.com/rusefi/rusefi/wiki/Acceleration_Compensation

**Comment by rusefillc** [comment]
See https://rusefi.com/forum/viewtopic.php?p=37546#p37546 for user feedback

**Comment by duhafnusa4** [comment]
old rusEFI wiki has these links now

https://github.com/rusefi/rusefi/wiki/Fuel-Overview

https://github.com/rusefi/rusefi/wiki/Cranking

If these are what @stefanst made (or wrote about) I will close the ticket.

tl;dr: @stefanst please let me know if I can close this ticket.
