### ISSUE TITLE
MRE main relay pictures put them somewhere

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#79]
@OrchardPerformance do we want to use these anywhere?

![image_from_ios](https://user-images.githubusercontent.com/48498823/90661158-d8a2e980-e214-11ea-9cbe-2fdef184c4a1.jpg)

![image_from_ios (1)](https://user-images.githubusercontent.com/48498823/90661048-ba3cee00-e214-11ea-93be-e6ad2f52d6b9.jpg)

**Comment by rusefillc** [comment]
the smarter one is 

![image](https://user-images.githubusercontent.com/48498823/90672739-94b7e080-e224-11ea-92fb-12a4fdc5b056.png)

**Comment by duhafnusa4** [comment]
diagram added to https://github.com/rusefi/rusefi/wiki/Hardware-microRusEFI

closing ticket.
