### ISSUE TITLE
auto ETB documentation

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi_documentation#81]
looks like 
https://github.com/rusefi/rusefi/wiki/HOWTO_electronic_throttle_body_configuration is not up to date

**Comment by rusefillc** [comment]
@mck1117 poke :)

**Comment by mck1117** [comment]
you mean like this? https://github.com/rusefi/rusefi/wiki/Electronic-Throttle-Body-Configuration-Guide
